// Code generated by ent, DO NOT EDIT.

package choice

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the choice type in the database.
	Label = "choice"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldIsCorrect holds the string denoting the is_correct field in the database.
	FieldIsCorrect = "is_correct"
	// FieldExplanation holds the string denoting the explanation field in the database.
	FieldExplanation = "explanation"
	// FieldSeq holds the string denoting the seq field in the database.
	FieldSeq = "seq"
	// FieldProblemTranslationID holds the string denoting the problem_translation_id field in the database.
	FieldProblemTranslationID = "problem_translation_id"
	// EdgeProblemTranslation holds the string denoting the problem_translation edge name in mutations.
	EdgeProblemTranslation = "problem_translation"
	// Table holds the table name of the choice in the database.
	Table = "choices"
	// ProblemTranslationTable is the table that holds the problem_translation relation/edge.
	ProblemTranslationTable = "choices"
	// ProblemTranslationInverseTable is the table name for the ProblemTranslation entity.
	// It exists in this package in order to avoid circular dependency with the "problemtranslation" package.
	ProblemTranslationInverseTable = "problem_translations"
	// ProblemTranslationColumn is the table column denoting the problem_translation relation/edge.
	ProblemTranslationColumn = "problem_translation_id"
)

// Columns holds all SQL columns for choice fields.
var Columns = []string{
	FieldID,
	FieldContent,
	FieldIsCorrect,
	FieldExplanation,
	FieldSeq,
	FieldProblemTranslationID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
	// DefaultIsCorrect holds the default value on creation for the "is_correct" field.
	DefaultIsCorrect bool
)

// OrderOption defines the ordering options for the Choice queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByIsCorrect orders the results by the is_correct field.
func ByIsCorrect(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsCorrect, opts...).ToFunc()
}

// ByExplanation orders the results by the explanation field.
func ByExplanation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExplanation, opts...).ToFunc()
}

// BySeq orders the results by the seq field.
func BySeq(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeq, opts...).ToFunc()
}

// ByProblemTranslationID orders the results by the problem_translation_id field.
func ByProblemTranslationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProblemTranslationID, opts...).ToFunc()
}

// ByProblemTranslationField orders the results by problem_translation field.
func ByProblemTranslationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProblemTranslationStep(), sql.OrderByField(field, opts...))
	}
}
func newProblemTranslationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProblemTranslationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProblemTranslationTable, ProblemTranslationColumn),
	)
}
