// Code generated by ent, DO NOT EDIT.

package choice

import (
	"examination/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Choice {
	return predicate.Choice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Choice {
	return predicate.Choice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Choice {
	return predicate.Choice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Choice {
	return predicate.Choice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Choice {
	return predicate.Choice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Choice {
	return predicate.Choice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Choice {
	return predicate.Choice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Choice {
	return predicate.Choice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Choice {
	return predicate.Choice(sql.FieldLTE(FieldID, id))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Choice {
	return predicate.Choice(sql.FieldEQ(FieldContent, v))
}

// IsCorrect applies equality check predicate on the "is_correct" field. It's identical to IsCorrectEQ.
func IsCorrect(v bool) predicate.Choice {
	return predicate.Choice(sql.FieldEQ(FieldIsCorrect, v))
}

// Explanation applies equality check predicate on the "explanation" field. It's identical to ExplanationEQ.
func Explanation(v string) predicate.Choice {
	return predicate.Choice(sql.FieldEQ(FieldExplanation, v))
}

// Seq applies equality check predicate on the "seq" field. It's identical to SeqEQ.
func Seq(v int) predicate.Choice {
	return predicate.Choice(sql.FieldEQ(FieldSeq, v))
}

// ProblemTranslationID applies equality check predicate on the "problem_translation_id" field. It's identical to ProblemTranslationIDEQ.
func ProblemTranslationID(v int) predicate.Choice {
	return predicate.Choice(sql.FieldEQ(FieldProblemTranslationID, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Choice {
	return predicate.Choice(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Choice {
	return predicate.Choice(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Choice {
	return predicate.Choice(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Choice {
	return predicate.Choice(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Choice {
	return predicate.Choice(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Choice {
	return predicate.Choice(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Choice {
	return predicate.Choice(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Choice {
	return predicate.Choice(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Choice {
	return predicate.Choice(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Choice {
	return predicate.Choice(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Choice {
	return predicate.Choice(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Choice {
	return predicate.Choice(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Choice {
	return predicate.Choice(sql.FieldContainsFold(FieldContent, v))
}

// IsCorrectEQ applies the EQ predicate on the "is_correct" field.
func IsCorrectEQ(v bool) predicate.Choice {
	return predicate.Choice(sql.FieldEQ(FieldIsCorrect, v))
}

// IsCorrectNEQ applies the NEQ predicate on the "is_correct" field.
func IsCorrectNEQ(v bool) predicate.Choice {
	return predicate.Choice(sql.FieldNEQ(FieldIsCorrect, v))
}

// ExplanationEQ applies the EQ predicate on the "explanation" field.
func ExplanationEQ(v string) predicate.Choice {
	return predicate.Choice(sql.FieldEQ(FieldExplanation, v))
}

// ExplanationNEQ applies the NEQ predicate on the "explanation" field.
func ExplanationNEQ(v string) predicate.Choice {
	return predicate.Choice(sql.FieldNEQ(FieldExplanation, v))
}

// ExplanationIn applies the In predicate on the "explanation" field.
func ExplanationIn(vs ...string) predicate.Choice {
	return predicate.Choice(sql.FieldIn(FieldExplanation, vs...))
}

// ExplanationNotIn applies the NotIn predicate on the "explanation" field.
func ExplanationNotIn(vs ...string) predicate.Choice {
	return predicate.Choice(sql.FieldNotIn(FieldExplanation, vs...))
}

// ExplanationGT applies the GT predicate on the "explanation" field.
func ExplanationGT(v string) predicate.Choice {
	return predicate.Choice(sql.FieldGT(FieldExplanation, v))
}

// ExplanationGTE applies the GTE predicate on the "explanation" field.
func ExplanationGTE(v string) predicate.Choice {
	return predicate.Choice(sql.FieldGTE(FieldExplanation, v))
}

// ExplanationLT applies the LT predicate on the "explanation" field.
func ExplanationLT(v string) predicate.Choice {
	return predicate.Choice(sql.FieldLT(FieldExplanation, v))
}

// ExplanationLTE applies the LTE predicate on the "explanation" field.
func ExplanationLTE(v string) predicate.Choice {
	return predicate.Choice(sql.FieldLTE(FieldExplanation, v))
}

// ExplanationContains applies the Contains predicate on the "explanation" field.
func ExplanationContains(v string) predicate.Choice {
	return predicate.Choice(sql.FieldContains(FieldExplanation, v))
}

// ExplanationHasPrefix applies the HasPrefix predicate on the "explanation" field.
func ExplanationHasPrefix(v string) predicate.Choice {
	return predicate.Choice(sql.FieldHasPrefix(FieldExplanation, v))
}

// ExplanationHasSuffix applies the HasSuffix predicate on the "explanation" field.
func ExplanationHasSuffix(v string) predicate.Choice {
	return predicate.Choice(sql.FieldHasSuffix(FieldExplanation, v))
}

// ExplanationIsNil applies the IsNil predicate on the "explanation" field.
func ExplanationIsNil() predicate.Choice {
	return predicate.Choice(sql.FieldIsNull(FieldExplanation))
}

// ExplanationNotNil applies the NotNil predicate on the "explanation" field.
func ExplanationNotNil() predicate.Choice {
	return predicate.Choice(sql.FieldNotNull(FieldExplanation))
}

// ExplanationEqualFold applies the EqualFold predicate on the "explanation" field.
func ExplanationEqualFold(v string) predicate.Choice {
	return predicate.Choice(sql.FieldEqualFold(FieldExplanation, v))
}

// ExplanationContainsFold applies the ContainsFold predicate on the "explanation" field.
func ExplanationContainsFold(v string) predicate.Choice {
	return predicate.Choice(sql.FieldContainsFold(FieldExplanation, v))
}

// SeqEQ applies the EQ predicate on the "seq" field.
func SeqEQ(v int) predicate.Choice {
	return predicate.Choice(sql.FieldEQ(FieldSeq, v))
}

// SeqNEQ applies the NEQ predicate on the "seq" field.
func SeqNEQ(v int) predicate.Choice {
	return predicate.Choice(sql.FieldNEQ(FieldSeq, v))
}

// SeqIn applies the In predicate on the "seq" field.
func SeqIn(vs ...int) predicate.Choice {
	return predicate.Choice(sql.FieldIn(FieldSeq, vs...))
}

// SeqNotIn applies the NotIn predicate on the "seq" field.
func SeqNotIn(vs ...int) predicate.Choice {
	return predicate.Choice(sql.FieldNotIn(FieldSeq, vs...))
}

// SeqGT applies the GT predicate on the "seq" field.
func SeqGT(v int) predicate.Choice {
	return predicate.Choice(sql.FieldGT(FieldSeq, v))
}

// SeqGTE applies the GTE predicate on the "seq" field.
func SeqGTE(v int) predicate.Choice {
	return predicate.Choice(sql.FieldGTE(FieldSeq, v))
}

// SeqLT applies the LT predicate on the "seq" field.
func SeqLT(v int) predicate.Choice {
	return predicate.Choice(sql.FieldLT(FieldSeq, v))
}

// SeqLTE applies the LTE predicate on the "seq" field.
func SeqLTE(v int) predicate.Choice {
	return predicate.Choice(sql.FieldLTE(FieldSeq, v))
}

// ProblemTranslationIDEQ applies the EQ predicate on the "problem_translation_id" field.
func ProblemTranslationIDEQ(v int) predicate.Choice {
	return predicate.Choice(sql.FieldEQ(FieldProblemTranslationID, v))
}

// ProblemTranslationIDNEQ applies the NEQ predicate on the "problem_translation_id" field.
func ProblemTranslationIDNEQ(v int) predicate.Choice {
	return predicate.Choice(sql.FieldNEQ(FieldProblemTranslationID, v))
}

// ProblemTranslationIDIn applies the In predicate on the "problem_translation_id" field.
func ProblemTranslationIDIn(vs ...int) predicate.Choice {
	return predicate.Choice(sql.FieldIn(FieldProblemTranslationID, vs...))
}

// ProblemTranslationIDNotIn applies the NotIn predicate on the "problem_translation_id" field.
func ProblemTranslationIDNotIn(vs ...int) predicate.Choice {
	return predicate.Choice(sql.FieldNotIn(FieldProblemTranslationID, vs...))
}

// HasProblemTranslation applies the HasEdge predicate on the "problem_translation" edge.
func HasProblemTranslation() predicate.Choice {
	return predicate.Choice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProblemTranslationTable, ProblemTranslationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProblemTranslationWith applies the HasEdge predicate on the "problem_translation" edge with a given conditions (other predicates).
func HasProblemTranslationWith(preds ...predicate.ProblemTranslation) predicate.Choice {
	return predicate.Choice(func(s *sql.Selector) {
		step := newProblemTranslationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Choice) predicate.Choice {
	return predicate.Choice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Choice) predicate.Choice {
	return predicate.Choice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Choice) predicate.Choice {
	return predicate.Choice(sql.NotPredicates(p))
}
