// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChoicesColumns holds the columns for the "choices" table.
	ChoicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "is_correct", Type: field.TypeBool, Default: false},
		{Name: "explanation", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "seq", Type: field.TypeInt},
		{Name: "problem_translation_id", Type: field.TypeInt},
	}
	// ChoicesTable holds the schema information for the "choices" table.
	ChoicesTable = &schema.Table{
		Name:       "choices",
		Columns:    ChoicesColumns,
		PrimaryKey: []*schema.Column{ChoicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "choices_problem_translations_choices",
				Columns:    []*schema.Column{ChoicesColumns[5]},
				RefColumns: []*schema.Column{ProblemTranslationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ExamsColumns holds the columns for the "exams" table.
	ExamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "time_limit", Type: field.TypeInt},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// ExamsTable holds the schema information for the "exams" table.
	ExamsTable = &schema.Table{
		Name:       "exams",
		Columns:    ExamsColumns,
		PrimaryKey: []*schema.Column{ExamsColumns[0]},
	}
	// ProblemsColumns holds the columns for the "problems" table.
	ProblemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"SOURCE", "VARIANT"}, Default: "SOURCE"},
		{Name: "difficulty", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "parent_id", Type: field.TypeInt, Nullable: true},
		{Name: "unit_id", Type: field.TypeInt},
	}
	// ProblemsTable holds the schema information for the "problems" table.
	ProblemsTable = &schema.Table{
		Name:       "problems",
		Columns:    ProblemsColumns,
		PrimaryKey: []*schema.Column{ProblemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "problems_problems_children",
				Columns:    []*schema.Column{ProblemsColumns[4]},
				RefColumns: []*schema.Column{ProblemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "problems_units_problems",
				Columns:    []*schema.Column{ProblemsColumns[5]},
				RefColumns: []*schema.Column{UnitsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ProblemTranslationsColumns holds the columns for the "problem_translations" table.
	ProblemTranslationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "locale", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "explanation", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "problem_id", Type: field.TypeInt},
	}
	// ProblemTranslationsTable holds the schema information for the "problem_translations" table.
	ProblemTranslationsTable = &schema.Table{
		Name:       "problem_translations",
		Columns:    ProblemTranslationsColumns,
		PrimaryKey: []*schema.Column{ProblemTranslationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "problem_translations_problems_translations",
				Columns:    []*schema.Column{ProblemTranslationsColumns[5]},
				RefColumns: []*schema.Column{ProblemsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "problemtranslation_problem_id_locale",
				Unique:  true,
				Columns: []*schema.Column{ProblemTranslationsColumns[5], ProblemTranslationsColumns[1]},
			},
		},
	}
	// SectionsColumns holds the columns for the "sections" table.
	SectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "seq", Type: field.TypeInt},
		{Name: "exam_id", Type: field.TypeInt},
	}
	// SectionsTable holds the schema information for the "sections" table.
	SectionsTable = &schema.Table{
		Name:       "sections",
		Columns:    SectionsColumns,
		PrimaryKey: []*schema.Column{SectionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sections_exams_sections",
				Columns:    []*schema.Column{SectionsColumns[3]},
				RefColumns: []*schema.Column{ExamsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TopicsColumns holds the columns for the "topics" table.
	TopicsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "seq", Type: field.TypeInt},
		{Name: "exam_id", Type: field.TypeInt},
		{Name: "section_id", Type: field.TypeInt, Nullable: true},
	}
	// TopicsTable holds the schema information for the "topics" table.
	TopicsTable = &schema.Table{
		Name:       "topics",
		Columns:    TopicsColumns,
		PrimaryKey: []*schema.Column{TopicsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "topics_exams_topics",
				Columns:    []*schema.Column{TopicsColumns[3]},
				RefColumns: []*schema.Column{ExamsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "topics_sections_topics",
				Columns:    []*schema.Column{TopicsColumns[4]},
				RefColumns: []*schema.Column{SectionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UnitsColumns holds the columns for the "units" table.
	UnitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "seq", Type: field.TypeInt},
		{Name: "exam_id", Type: field.TypeInt},
		{Name: "section_id", Type: field.TypeInt, Nullable: true},
		{Name: "topic_id", Type: field.TypeInt, Nullable: true},
	}
	// UnitsTable holds the schema information for the "units" table.
	UnitsTable = &schema.Table{
		Name:       "units",
		Columns:    UnitsColumns,
		PrimaryKey: []*schema.Column{UnitsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "units_exams_units",
				Columns:    []*schema.Column{UnitsColumns[3]},
				RefColumns: []*schema.Column{ExamsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "units_sections_units",
				Columns:    []*schema.Column{UnitsColumns[4]},
				RefColumns: []*schema.Column{SectionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "units_topics_units",
				Columns:    []*schema.Column{UnitsColumns[5]},
				RefColumns: []*schema.Column{TopicsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// VersionRulesColumns holds the columns for the "version_rules" table.
	VersionRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "year", Type: field.TypeInt, Nullable: true},
		{Name: "round", Type: field.TypeInt, Nullable: true},
		{Name: "category", Type: field.TypeString, Nullable: true},
		{Name: "operator", Type: field.TypeEnum, Enums: []string{"GT", "GTE", "LT", "LTE", "EQ", "NEQ"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"ACTIVE", "DEPRECATED"}, Default: "ACTIVE"},
		{Name: "exam_id", Type: field.TypeInt},
		{Name: "problem_id", Type: field.TypeInt, Nullable: true},
	}
	// VersionRulesTable holds the schema information for the "version_rules" table.
	VersionRulesTable = &schema.Table{
		Name:       "version_rules",
		Columns:    VersionRulesColumns,
		PrimaryKey: []*schema.Column{VersionRulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "version_rules_exams_version_rules",
				Columns:    []*schema.Column{VersionRulesColumns[6]},
				RefColumns: []*schema.Column{ExamsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "version_rules_problems_versions",
				Columns:    []*schema.Column{VersionRulesColumns[7]},
				RefColumns: []*schema.Column{ProblemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChoicesTable,
		ExamsTable,
		ProblemsTable,
		ProblemTranslationsTable,
		SectionsTable,
		TopicsTable,
		UnitsTable,
		VersionRulesTable,
	}
)

func init() {
	ChoicesTable.ForeignKeys[0].RefTable = ProblemTranslationsTable
	ProblemsTable.ForeignKeys[0].RefTable = ProblemsTable
	ProblemsTable.ForeignKeys[1].RefTable = UnitsTable
	ProblemTranslationsTable.ForeignKeys[0].RefTable = ProblemsTable
	SectionsTable.ForeignKeys[0].RefTable = ExamsTable
	TopicsTable.ForeignKeys[0].RefTable = ExamsTable
	TopicsTable.ForeignKeys[1].RefTable = SectionsTable
	UnitsTable.ForeignKeys[0].RefTable = ExamsTable
	UnitsTable.ForeignKeys[1].RefTable = SectionsTable
	UnitsTable.ForeignKeys[2].RefTable = TopicsTable
	VersionRulesTable.ForeignKeys[0].RefTable = ExamsTable
	VersionRulesTable.ForeignKeys[1].RefTable = ProblemsTable
}
