// Code generated by ent, DO NOT EDIT.

package ent

import (
	"examination/internal/ent/choice"
	"examination/internal/ent/problemtranslation"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Choice is the model entity for the Choice schema.
type Choice struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// IsCorrect holds the value of the "is_correct" field.
	IsCorrect bool `json:"is_correct,omitempty"`
	// Explanation holds the value of the "explanation" field.
	Explanation string `json:"explanation,omitempty"`
	// Sequence order
	Seq int `json:"seq,omitempty"`
	// ProblemTranslationID holds the value of the "problem_translation_id" field.
	ProblemTranslationID int `json:"problem_translation_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChoiceQuery when eager-loading is set.
	Edges        ChoiceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChoiceEdges holds the relations/edges for other nodes in the graph.
type ChoiceEdges struct {
	// ProblemTranslation holds the value of the problem_translation edge.
	ProblemTranslation *ProblemTranslation `json:"problem_translation,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProblemTranslationOrErr returns the ProblemTranslation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChoiceEdges) ProblemTranslationOrErr() (*ProblemTranslation, error) {
	if e.ProblemTranslation != nil {
		return e.ProblemTranslation, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: problemtranslation.Label}
	}
	return nil, &NotLoadedError{edge: "problem_translation"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Choice) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case choice.FieldIsCorrect:
			values[i] = new(sql.NullBool)
		case choice.FieldID, choice.FieldSeq, choice.FieldProblemTranslationID:
			values[i] = new(sql.NullInt64)
		case choice.FieldContent, choice.FieldExplanation:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Choice fields.
func (_m *Choice) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case choice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case choice.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case choice.FieldIsCorrect:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_correct", values[i])
			} else if value.Valid {
				_m.IsCorrect = value.Bool
			}
		case choice.FieldExplanation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field explanation", values[i])
			} else if value.Valid {
				_m.Explanation = value.String
			}
		case choice.FieldSeq:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field seq", values[i])
			} else if value.Valid {
				_m.Seq = int(value.Int64)
			}
		case choice.FieldProblemTranslationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field problem_translation_id", values[i])
			} else if value.Valid {
				_m.ProblemTranslationID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Choice.
// This includes values selected through modifiers, order, etc.
func (_m *Choice) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProblemTranslation queries the "problem_translation" edge of the Choice entity.
func (_m *Choice) QueryProblemTranslation() *ProblemTranslationQuery {
	return NewChoiceClient(_m.config).QueryProblemTranslation(_m)
}

// Update returns a builder for updating this Choice.
// Note that you need to call Choice.Unwrap() before calling this method if this Choice
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Choice) Update() *ChoiceUpdateOne {
	return NewChoiceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Choice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Choice) Unwrap() *Choice {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Choice is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Choice) String() string {
	var builder strings.Builder
	builder.WriteString("Choice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("is_correct=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsCorrect))
	builder.WriteString(", ")
	builder.WriteString("explanation=")
	builder.WriteString(_m.Explanation)
	builder.WriteString(", ")
	builder.WriteString("seq=")
	builder.WriteString(fmt.Sprintf("%v", _m.Seq))
	builder.WriteString(", ")
	builder.WriteString("problem_translation_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProblemTranslationID))
	builder.WriteByte(')')
	return builder.String()
}

// Choices is a parsable slice of Choice.
type Choices []*Choice
