// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"examination/internal/ent/choice"
	"examination/internal/ent/predicate"
	"examination/internal/ent/problemtranslation"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChoiceQuery is the builder for querying Choice entities.
type ChoiceQuery struct {
	config
	ctx                    *QueryContext
	order                  []choice.OrderOption
	inters                 []Interceptor
	predicates             []predicate.Choice
	withProblemTranslation *ProblemTranslationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChoiceQuery builder.
func (_q *ChoiceQuery) Where(ps ...predicate.Choice) *ChoiceQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChoiceQuery) Limit(limit int) *ChoiceQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChoiceQuery) Offset(offset int) *ChoiceQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChoiceQuery) Unique(unique bool) *ChoiceQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChoiceQuery) Order(o ...choice.OrderOption) *ChoiceQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProblemTranslation chains the current query on the "problem_translation" edge.
func (_q *ChoiceQuery) QueryProblemTranslation() *ProblemTranslationQuery {
	query := (&ProblemTranslationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(choice.Table, choice.FieldID, selector),
			sqlgraph.To(problemtranslation.Table, problemtranslation.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, choice.ProblemTranslationTable, choice.ProblemTranslationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Choice entity from the query.
// Returns a *NotFoundError when no Choice was found.
func (_q *ChoiceQuery) First(ctx context.Context) (*Choice, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{choice.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChoiceQuery) FirstX(ctx context.Context) *Choice {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Choice ID from the query.
// Returns a *NotFoundError when no Choice ID was found.
func (_q *ChoiceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{choice.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChoiceQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Choice entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Choice entity is found.
// Returns a *NotFoundError when no Choice entities are found.
func (_q *ChoiceQuery) Only(ctx context.Context) (*Choice, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{choice.Label}
	default:
		return nil, &NotSingularError{choice.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChoiceQuery) OnlyX(ctx context.Context) *Choice {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Choice ID in the query.
// Returns a *NotSingularError when more than one Choice ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChoiceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{choice.Label}
	default:
		err = &NotSingularError{choice.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChoiceQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Choices.
func (_q *ChoiceQuery) All(ctx context.Context) ([]*Choice, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Choice, *ChoiceQuery]()
	return withInterceptors[[]*Choice](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChoiceQuery) AllX(ctx context.Context) []*Choice {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Choice IDs.
func (_q *ChoiceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(choice.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChoiceQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChoiceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChoiceQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChoiceQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChoiceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChoiceQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChoiceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChoiceQuery) Clone() *ChoiceQuery {
	if _q == nil {
		return nil
	}
	return &ChoiceQuery{
		config:                 _q.config,
		ctx:                    _q.ctx.Clone(),
		order:                  append([]choice.OrderOption{}, _q.order...),
		inters:                 append([]Interceptor{}, _q.inters...),
		predicates:             append([]predicate.Choice{}, _q.predicates...),
		withProblemTranslation: _q.withProblemTranslation.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProblemTranslation tells the query-builder to eager-load the nodes that are connected to
// the "problem_translation" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChoiceQuery) WithProblemTranslation(opts ...func(*ProblemTranslationQuery)) *ChoiceQuery {
	query := (&ProblemTranslationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProblemTranslation = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Content string `json:"content,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Choice.Query().
//		GroupBy(choice.FieldContent).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChoiceQuery) GroupBy(field string, fields ...string) *ChoiceGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChoiceGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = choice.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Content string `json:"content,omitempty"`
//	}
//
//	client.Choice.Query().
//		Select(choice.FieldContent).
//		Scan(ctx, &v)
func (_q *ChoiceQuery) Select(fields ...string) *ChoiceSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChoiceSelect{ChoiceQuery: _q}
	sbuild.label = choice.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChoiceSelect configured with the given aggregations.
func (_q *ChoiceQuery) Aggregate(fns ...AggregateFunc) *ChoiceSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChoiceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !choice.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChoiceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Choice, error) {
	var (
		nodes       = []*Choice{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withProblemTranslation != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Choice).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Choice{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProblemTranslation; query != nil {
		if err := _q.loadProblemTranslation(ctx, query, nodes, nil,
			func(n *Choice, e *ProblemTranslation) { n.Edges.ProblemTranslation = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChoiceQuery) loadProblemTranslation(ctx context.Context, query *ProblemTranslationQuery, nodes []*Choice, init func(*Choice), assign func(*Choice, *ProblemTranslation)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Choice)
	for i := range nodes {
		fk := nodes[i].ProblemTranslationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(problemtranslation.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "problem_translation_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ChoiceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChoiceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(choice.Table, choice.Columns, sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, choice.FieldID)
		for i := range fields {
			if fields[i] != choice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProblemTranslation != nil {
			_spec.Node.AddColumnOnce(choice.FieldProblemTranslationID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChoiceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(choice.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = choice.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChoiceGroupBy is the group-by builder for Choice entities.
type ChoiceGroupBy struct {
	selector
	build *ChoiceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChoiceGroupBy) Aggregate(fns ...AggregateFunc) *ChoiceGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChoiceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChoiceQuery, *ChoiceGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChoiceGroupBy) sqlScan(ctx context.Context, root *ChoiceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChoiceSelect is the builder for selecting fields of Choice entities.
type ChoiceSelect struct {
	*ChoiceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChoiceSelect) Aggregate(fns ...AggregateFunc) *ChoiceSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChoiceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChoiceQuery, *ChoiceSelect](ctx, _s.ChoiceQuery, _s, _s.inters, v)
}

func (_s *ChoiceSelect) sqlScan(ctx context.Context, root *ChoiceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
