// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"examination/internal/ent/choice"
	"examination/internal/ent/predicate"
	"examination/internal/ent/problemtranslation"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChoiceUpdate is the builder for updating Choice entities.
type ChoiceUpdate struct {
	config
	hooks    []Hook
	mutation *ChoiceMutation
}

// Where appends a list predicates to the ChoiceUpdate builder.
func (_u *ChoiceUpdate) Where(ps ...predicate.Choice) *ChoiceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContent sets the "content" field.
func (_u *ChoiceUpdate) SetContent(v string) *ChoiceUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChoiceUpdate) SetNillableContent(v *string) *ChoiceUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetIsCorrect sets the "is_correct" field.
func (_u *ChoiceUpdate) SetIsCorrect(v bool) *ChoiceUpdate {
	_u.mutation.SetIsCorrect(v)
	return _u
}

// SetNillableIsCorrect sets the "is_correct" field if the given value is not nil.
func (_u *ChoiceUpdate) SetNillableIsCorrect(v *bool) *ChoiceUpdate {
	if v != nil {
		_u.SetIsCorrect(*v)
	}
	return _u
}

// SetExplanation sets the "explanation" field.
func (_u *ChoiceUpdate) SetExplanation(v string) *ChoiceUpdate {
	_u.mutation.SetExplanation(v)
	return _u
}

// SetNillableExplanation sets the "explanation" field if the given value is not nil.
func (_u *ChoiceUpdate) SetNillableExplanation(v *string) *ChoiceUpdate {
	if v != nil {
		_u.SetExplanation(*v)
	}
	return _u
}

// ClearExplanation clears the value of the "explanation" field.
func (_u *ChoiceUpdate) ClearExplanation() *ChoiceUpdate {
	_u.mutation.ClearExplanation()
	return _u
}

// SetSeq sets the "seq" field.
func (_u *ChoiceUpdate) SetSeq(v int) *ChoiceUpdate {
	_u.mutation.ResetSeq()
	_u.mutation.SetSeq(v)
	return _u
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_u *ChoiceUpdate) SetNillableSeq(v *int) *ChoiceUpdate {
	if v != nil {
		_u.SetSeq(*v)
	}
	return _u
}

// AddSeq adds value to the "seq" field.
func (_u *ChoiceUpdate) AddSeq(v int) *ChoiceUpdate {
	_u.mutation.AddSeq(v)
	return _u
}

// SetProblemTranslationID sets the "problem_translation_id" field.
func (_u *ChoiceUpdate) SetProblemTranslationID(v int) *ChoiceUpdate {
	_u.mutation.SetProblemTranslationID(v)
	return _u
}

// SetNillableProblemTranslationID sets the "problem_translation_id" field if the given value is not nil.
func (_u *ChoiceUpdate) SetNillableProblemTranslationID(v *int) *ChoiceUpdate {
	if v != nil {
		_u.SetProblemTranslationID(*v)
	}
	return _u
}

// SetProblemTranslation sets the "problem_translation" edge to the ProblemTranslation entity.
func (_u *ChoiceUpdate) SetProblemTranslation(v *ProblemTranslation) *ChoiceUpdate {
	return _u.SetProblemTranslationID(v.ID)
}

// Mutation returns the ChoiceMutation object of the builder.
func (_u *ChoiceUpdate) Mutation() *ChoiceMutation {
	return _u.mutation
}

// ClearProblemTranslation clears the "problem_translation" edge to the ProblemTranslation entity.
func (_u *ChoiceUpdate) ClearProblemTranslation() *ChoiceUpdate {
	_u.mutation.ClearProblemTranslation()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChoiceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChoiceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChoiceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChoiceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChoiceUpdate) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := choice.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Choice.content": %w`, err)}
		}
	}
	if _u.mutation.ProblemTranslationCleared() && len(_u.mutation.ProblemTranslationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Choice.problem_translation"`)
	}
	return nil
}

func (_u *ChoiceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(choice.Table, choice.Columns, sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(choice.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsCorrect(); ok {
		_spec.SetField(choice.FieldIsCorrect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Explanation(); ok {
		_spec.SetField(choice.FieldExplanation, field.TypeString, value)
	}
	if _u.mutation.ExplanationCleared() {
		_spec.ClearField(choice.FieldExplanation, field.TypeString)
	}
	if value, ok := _u.mutation.Seq(); ok {
		_spec.SetField(choice.FieldSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeq(); ok {
		_spec.AddField(choice.FieldSeq, field.TypeInt, value)
	}
	if _u.mutation.ProblemTranslationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.ProblemTranslationTable,
			Columns: []string{choice.ProblemTranslationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problemtranslation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemTranslationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.ProblemTranslationTable,
			Columns: []string{choice.ProblemTranslationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problemtranslation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{choice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChoiceUpdateOne is the builder for updating a single Choice entity.
type ChoiceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChoiceMutation
}

// SetContent sets the "content" field.
func (_u *ChoiceUpdateOne) SetContent(v string) *ChoiceUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChoiceUpdateOne) SetNillableContent(v *string) *ChoiceUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetIsCorrect sets the "is_correct" field.
func (_u *ChoiceUpdateOne) SetIsCorrect(v bool) *ChoiceUpdateOne {
	_u.mutation.SetIsCorrect(v)
	return _u
}

// SetNillableIsCorrect sets the "is_correct" field if the given value is not nil.
func (_u *ChoiceUpdateOne) SetNillableIsCorrect(v *bool) *ChoiceUpdateOne {
	if v != nil {
		_u.SetIsCorrect(*v)
	}
	return _u
}

// SetExplanation sets the "explanation" field.
func (_u *ChoiceUpdateOne) SetExplanation(v string) *ChoiceUpdateOne {
	_u.mutation.SetExplanation(v)
	return _u
}

// SetNillableExplanation sets the "explanation" field if the given value is not nil.
func (_u *ChoiceUpdateOne) SetNillableExplanation(v *string) *ChoiceUpdateOne {
	if v != nil {
		_u.SetExplanation(*v)
	}
	return _u
}

// ClearExplanation clears the value of the "explanation" field.
func (_u *ChoiceUpdateOne) ClearExplanation() *ChoiceUpdateOne {
	_u.mutation.ClearExplanation()
	return _u
}

// SetSeq sets the "seq" field.
func (_u *ChoiceUpdateOne) SetSeq(v int) *ChoiceUpdateOne {
	_u.mutation.ResetSeq()
	_u.mutation.SetSeq(v)
	return _u
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_u *ChoiceUpdateOne) SetNillableSeq(v *int) *ChoiceUpdateOne {
	if v != nil {
		_u.SetSeq(*v)
	}
	return _u
}

// AddSeq adds value to the "seq" field.
func (_u *ChoiceUpdateOne) AddSeq(v int) *ChoiceUpdateOne {
	_u.mutation.AddSeq(v)
	return _u
}

// SetProblemTranslationID sets the "problem_translation_id" field.
func (_u *ChoiceUpdateOne) SetProblemTranslationID(v int) *ChoiceUpdateOne {
	_u.mutation.SetProblemTranslationID(v)
	return _u
}

// SetNillableProblemTranslationID sets the "problem_translation_id" field if the given value is not nil.
func (_u *ChoiceUpdateOne) SetNillableProblemTranslationID(v *int) *ChoiceUpdateOne {
	if v != nil {
		_u.SetProblemTranslationID(*v)
	}
	return _u
}

// SetProblemTranslation sets the "problem_translation" edge to the ProblemTranslation entity.
func (_u *ChoiceUpdateOne) SetProblemTranslation(v *ProblemTranslation) *ChoiceUpdateOne {
	return _u.SetProblemTranslationID(v.ID)
}

// Mutation returns the ChoiceMutation object of the builder.
func (_u *ChoiceUpdateOne) Mutation() *ChoiceMutation {
	return _u.mutation
}

// ClearProblemTranslation clears the "problem_translation" edge to the ProblemTranslation entity.
func (_u *ChoiceUpdateOne) ClearProblemTranslation() *ChoiceUpdateOne {
	_u.mutation.ClearProblemTranslation()
	return _u
}

// Where appends a list predicates to the ChoiceUpdate builder.
func (_u *ChoiceUpdateOne) Where(ps ...predicate.Choice) *ChoiceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChoiceUpdateOne) Select(field string, fields ...string) *ChoiceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Choice entity.
func (_u *ChoiceUpdateOne) Save(ctx context.Context) (*Choice, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChoiceUpdateOne) SaveX(ctx context.Context) *Choice {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChoiceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChoiceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChoiceUpdateOne) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := choice.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Choice.content": %w`, err)}
		}
	}
	if _u.mutation.ProblemTranslationCleared() && len(_u.mutation.ProblemTranslationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Choice.problem_translation"`)
	}
	return nil
}

func (_u *ChoiceUpdateOne) sqlSave(ctx context.Context) (_node *Choice, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(choice.Table, choice.Columns, sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Choice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, choice.FieldID)
		for _, f := range fields {
			if !choice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != choice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(choice.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsCorrect(); ok {
		_spec.SetField(choice.FieldIsCorrect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Explanation(); ok {
		_spec.SetField(choice.FieldExplanation, field.TypeString, value)
	}
	if _u.mutation.ExplanationCleared() {
		_spec.ClearField(choice.FieldExplanation, field.TypeString)
	}
	if value, ok := _u.mutation.Seq(); ok {
		_spec.SetField(choice.FieldSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeq(); ok {
		_spec.AddField(choice.FieldSeq, field.TypeInt, value)
	}
	if _u.mutation.ProblemTranslationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.ProblemTranslationTable,
			Columns: []string{choice.ProblemTranslationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problemtranslation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemTranslationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.ProblemTranslationTable,
			Columns: []string{choice.ProblemTranslationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problemtranslation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Choice{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{choice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
