// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"examination/internal/ent/exam"
	"examination/internal/ent/section"
	"examination/internal/ent/topic"
	"examination/internal/ent/unit"
	"examination/internal/ent/versionrule"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExamCreate is the builder for creating a Exam entity.
type ExamCreate struct {
	config
	mutation *ExamMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *ExamCreate) SetTitle(v string) *ExamCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ExamCreate) SetDescription(v string) *ExamCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ExamCreate) SetNillableDescription(v *string) *ExamCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetTimeLimit sets the "time_limit" field.
func (_c *ExamCreate) SetTimeLimit(v int) *ExamCreate {
	_c.mutation.SetTimeLimit(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *ExamCreate) SetIsActive(v bool) *ExamCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *ExamCreate) SetNillableIsActive(v *bool) *ExamCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// AddSectionIDs adds the "sections" edge to the Section entity by IDs.
func (_c *ExamCreate) AddSectionIDs(ids ...int) *ExamCreate {
	_c.mutation.AddSectionIDs(ids...)
	return _c
}

// AddSections adds the "sections" edges to the Section entity.
func (_c *ExamCreate) AddSections(v ...*Section) *ExamCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSectionIDs(ids...)
}

// AddTopicIDs adds the "topics" edge to the Topic entity by IDs.
func (_c *ExamCreate) AddTopicIDs(ids ...int) *ExamCreate {
	_c.mutation.AddTopicIDs(ids...)
	return _c
}

// AddTopics adds the "topics" edges to the Topic entity.
func (_c *ExamCreate) AddTopics(v ...*Topic) *ExamCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTopicIDs(ids...)
}

// AddUnitIDs adds the "units" edge to the Unit entity by IDs.
func (_c *ExamCreate) AddUnitIDs(ids ...int) *ExamCreate {
	_c.mutation.AddUnitIDs(ids...)
	return _c
}

// AddUnits adds the "units" edges to the Unit entity.
func (_c *ExamCreate) AddUnits(v ...*Unit) *ExamCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUnitIDs(ids...)
}

// AddVersionRuleIDs adds the "version_rules" edge to the VersionRule entity by IDs.
func (_c *ExamCreate) AddVersionRuleIDs(ids ...int) *ExamCreate {
	_c.mutation.AddVersionRuleIDs(ids...)
	return _c
}

// AddVersionRules adds the "version_rules" edges to the VersionRule entity.
func (_c *ExamCreate) AddVersionRules(v ...*VersionRule) *ExamCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVersionRuleIDs(ids...)
}

// Mutation returns the ExamMutation object of the builder.
func (_c *ExamCreate) Mutation() *ExamMutation {
	return _c.mutation
}

// Save creates the Exam in the database.
func (_c *ExamCreate) Save(ctx context.Context) (*Exam, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExamCreate) SaveX(ctx context.Context) *Exam {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExamCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExamCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExamCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := exam.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExamCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Exam.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := exam.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Exam.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TimeLimit(); !ok {
		return &ValidationError{Name: "time_limit", err: errors.New(`ent: missing required field "Exam.time_limit"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Exam.is_active"`)}
	}
	return nil
}

func (_c *ExamCreate) sqlSave(ctx context.Context) (*Exam, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExamCreate) createSpec() (*Exam, *sqlgraph.CreateSpec) {
	var (
		_node = &Exam{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(exam.Table, sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(exam.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(exam.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.TimeLimit(); ok {
		_spec.SetField(exam.FieldTimeLimit, field.TypeInt, value)
		_node.TimeLimit = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(exam.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if nodes := _c.mutation.SectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.SectionsTable,
			Columns: []string{exam.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TopicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.TopicsTable,
			Columns: []string{exam.TopicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.UnitsTable,
			Columns: []string{exam.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VersionRulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.VersionRulesTable,
			Columns: []string{exam.VersionRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(versionrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ExamCreateBulk is the builder for creating many Exam entities in bulk.
type ExamCreateBulk struct {
	config
	err      error
	builders []*ExamCreate
}

// Save creates the Exam entities in the database.
func (_c *ExamCreateBulk) Save(ctx context.Context) ([]*Exam, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Exam, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExamCreateBulk) SaveX(ctx context.Context) []*Exam {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExamCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExamCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
