// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"examination/internal/ent/exam"
	"examination/internal/ent/predicate"
	"examination/internal/ent/section"
	"examination/internal/ent/topic"
	"examination/internal/ent/unit"
	"examination/internal/ent/versionrule"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExamUpdate is the builder for updating Exam entities.
type ExamUpdate struct {
	config
	hooks    []Hook
	mutation *ExamMutation
}

// Where appends a list predicates to the ExamUpdate builder.
func (_u *ExamUpdate) Where(ps ...predicate.Exam) *ExamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ExamUpdate) SetTitle(v string) *ExamUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ExamUpdate) SetNillableTitle(v *string) *ExamUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ExamUpdate) SetDescription(v string) *ExamUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ExamUpdate) SetNillableDescription(v *string) *ExamUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ExamUpdate) ClearDescription() *ExamUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetTimeLimit sets the "time_limit" field.
func (_u *ExamUpdate) SetTimeLimit(v int) *ExamUpdate {
	_u.mutation.ResetTimeLimit()
	_u.mutation.SetTimeLimit(v)
	return _u
}

// SetNillableTimeLimit sets the "time_limit" field if the given value is not nil.
func (_u *ExamUpdate) SetNillableTimeLimit(v *int) *ExamUpdate {
	if v != nil {
		_u.SetTimeLimit(*v)
	}
	return _u
}

// AddTimeLimit adds value to the "time_limit" field.
func (_u *ExamUpdate) AddTimeLimit(v int) *ExamUpdate {
	_u.mutation.AddTimeLimit(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ExamUpdate) SetIsActive(v bool) *ExamUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ExamUpdate) SetNillableIsActive(v *bool) *ExamUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// AddSectionIDs adds the "sections" edge to the Section entity by IDs.
func (_u *ExamUpdate) AddSectionIDs(ids ...int) *ExamUpdate {
	_u.mutation.AddSectionIDs(ids...)
	return _u
}

// AddSections adds the "sections" edges to the Section entity.
func (_u *ExamUpdate) AddSections(v ...*Section) *ExamUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSectionIDs(ids...)
}

// AddTopicIDs adds the "topics" edge to the Topic entity by IDs.
func (_u *ExamUpdate) AddTopicIDs(ids ...int) *ExamUpdate {
	_u.mutation.AddTopicIDs(ids...)
	return _u
}

// AddTopics adds the "topics" edges to the Topic entity.
func (_u *ExamUpdate) AddTopics(v ...*Topic) *ExamUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTopicIDs(ids...)
}

// AddUnitIDs adds the "units" edge to the Unit entity by IDs.
func (_u *ExamUpdate) AddUnitIDs(ids ...int) *ExamUpdate {
	_u.mutation.AddUnitIDs(ids...)
	return _u
}

// AddUnits adds the "units" edges to the Unit entity.
func (_u *ExamUpdate) AddUnits(v ...*Unit) *ExamUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUnitIDs(ids...)
}

// AddVersionRuleIDs adds the "version_rules" edge to the VersionRule entity by IDs.
func (_u *ExamUpdate) AddVersionRuleIDs(ids ...int) *ExamUpdate {
	_u.mutation.AddVersionRuleIDs(ids...)
	return _u
}

// AddVersionRules adds the "version_rules" edges to the VersionRule entity.
func (_u *ExamUpdate) AddVersionRules(v ...*VersionRule) *ExamUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionRuleIDs(ids...)
}

// Mutation returns the ExamMutation object of the builder.
func (_u *ExamUpdate) Mutation() *ExamMutation {
	return _u.mutation
}

// ClearSections clears all "sections" edges to the Section entity.
func (_u *ExamUpdate) ClearSections() *ExamUpdate {
	_u.mutation.ClearSections()
	return _u
}

// RemoveSectionIDs removes the "sections" edge to Section entities by IDs.
func (_u *ExamUpdate) RemoveSectionIDs(ids ...int) *ExamUpdate {
	_u.mutation.RemoveSectionIDs(ids...)
	return _u
}

// RemoveSections removes "sections" edges to Section entities.
func (_u *ExamUpdate) RemoveSections(v ...*Section) *ExamUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSectionIDs(ids...)
}

// ClearTopics clears all "topics" edges to the Topic entity.
func (_u *ExamUpdate) ClearTopics() *ExamUpdate {
	_u.mutation.ClearTopics()
	return _u
}

// RemoveTopicIDs removes the "topics" edge to Topic entities by IDs.
func (_u *ExamUpdate) RemoveTopicIDs(ids ...int) *ExamUpdate {
	_u.mutation.RemoveTopicIDs(ids...)
	return _u
}

// RemoveTopics removes "topics" edges to Topic entities.
func (_u *ExamUpdate) RemoveTopics(v ...*Topic) *ExamUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTopicIDs(ids...)
}

// ClearUnits clears all "units" edges to the Unit entity.
func (_u *ExamUpdate) ClearUnits() *ExamUpdate {
	_u.mutation.ClearUnits()
	return _u
}

// RemoveUnitIDs removes the "units" edge to Unit entities by IDs.
func (_u *ExamUpdate) RemoveUnitIDs(ids ...int) *ExamUpdate {
	_u.mutation.RemoveUnitIDs(ids...)
	return _u
}

// RemoveUnits removes "units" edges to Unit entities.
func (_u *ExamUpdate) RemoveUnits(v ...*Unit) *ExamUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUnitIDs(ids...)
}

// ClearVersionRules clears all "version_rules" edges to the VersionRule entity.
func (_u *ExamUpdate) ClearVersionRules() *ExamUpdate {
	_u.mutation.ClearVersionRules()
	return _u
}

// RemoveVersionRuleIDs removes the "version_rules" edge to VersionRule entities by IDs.
func (_u *ExamUpdate) RemoveVersionRuleIDs(ids ...int) *ExamUpdate {
	_u.mutation.RemoveVersionRuleIDs(ids...)
	return _u
}

// RemoveVersionRules removes "version_rules" edges to VersionRule entities.
func (_u *ExamUpdate) RemoveVersionRules(v ...*VersionRule) *ExamUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionRuleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExamUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExamUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := exam.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Exam.title": %w`, err)}
		}
	}
	return nil
}

func (_u *ExamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(exam.Table, exam.Columns, sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(exam.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(exam.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(exam.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.TimeLimit(); ok {
		_spec.SetField(exam.FieldTimeLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeLimit(); ok {
		_spec.AddField(exam.FieldTimeLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(exam.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.SectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.SectionsTable,
			Columns: []string{exam.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSectionsIDs(); len(nodes) > 0 && !_u.mutation.SectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.SectionsTable,
			Columns: []string{exam.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.SectionsTable,
			Columns: []string{exam.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TopicsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.TopicsTable,
			Columns: []string{exam.TopicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTopicsIDs(); len(nodes) > 0 && !_u.mutation.TopicsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.TopicsTable,
			Columns: []string{exam.TopicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TopicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.TopicsTable,
			Columns: []string{exam.TopicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.UnitsTable,
			Columns: []string{exam.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUnitsIDs(); len(nodes) > 0 && !_u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.UnitsTable,
			Columns: []string{exam.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.UnitsTable,
			Columns: []string{exam.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.VersionRulesTable,
			Columns: []string{exam.VersionRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(versionrule.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionRulesIDs(); len(nodes) > 0 && !_u.mutation.VersionRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.VersionRulesTable,
			Columns: []string{exam.VersionRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(versionrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionRulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.VersionRulesTable,
			Columns: []string{exam.VersionRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(versionrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exam.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExamUpdateOne is the builder for updating a single Exam entity.
type ExamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExamMutation
}

// SetTitle sets the "title" field.
func (_u *ExamUpdateOne) SetTitle(v string) *ExamUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ExamUpdateOne) SetNillableTitle(v *string) *ExamUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ExamUpdateOne) SetDescription(v string) *ExamUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ExamUpdateOne) SetNillableDescription(v *string) *ExamUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ExamUpdateOne) ClearDescription() *ExamUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetTimeLimit sets the "time_limit" field.
func (_u *ExamUpdateOne) SetTimeLimit(v int) *ExamUpdateOne {
	_u.mutation.ResetTimeLimit()
	_u.mutation.SetTimeLimit(v)
	return _u
}

// SetNillableTimeLimit sets the "time_limit" field if the given value is not nil.
func (_u *ExamUpdateOne) SetNillableTimeLimit(v *int) *ExamUpdateOne {
	if v != nil {
		_u.SetTimeLimit(*v)
	}
	return _u
}

// AddTimeLimit adds value to the "time_limit" field.
func (_u *ExamUpdateOne) AddTimeLimit(v int) *ExamUpdateOne {
	_u.mutation.AddTimeLimit(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ExamUpdateOne) SetIsActive(v bool) *ExamUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ExamUpdateOne) SetNillableIsActive(v *bool) *ExamUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// AddSectionIDs adds the "sections" edge to the Section entity by IDs.
func (_u *ExamUpdateOne) AddSectionIDs(ids ...int) *ExamUpdateOne {
	_u.mutation.AddSectionIDs(ids...)
	return _u
}

// AddSections adds the "sections" edges to the Section entity.
func (_u *ExamUpdateOne) AddSections(v ...*Section) *ExamUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSectionIDs(ids...)
}

// AddTopicIDs adds the "topics" edge to the Topic entity by IDs.
func (_u *ExamUpdateOne) AddTopicIDs(ids ...int) *ExamUpdateOne {
	_u.mutation.AddTopicIDs(ids...)
	return _u
}

// AddTopics adds the "topics" edges to the Topic entity.
func (_u *ExamUpdateOne) AddTopics(v ...*Topic) *ExamUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTopicIDs(ids...)
}

// AddUnitIDs adds the "units" edge to the Unit entity by IDs.
func (_u *ExamUpdateOne) AddUnitIDs(ids ...int) *ExamUpdateOne {
	_u.mutation.AddUnitIDs(ids...)
	return _u
}

// AddUnits adds the "units" edges to the Unit entity.
func (_u *ExamUpdateOne) AddUnits(v ...*Unit) *ExamUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUnitIDs(ids...)
}

// AddVersionRuleIDs adds the "version_rules" edge to the VersionRule entity by IDs.
func (_u *ExamUpdateOne) AddVersionRuleIDs(ids ...int) *ExamUpdateOne {
	_u.mutation.AddVersionRuleIDs(ids...)
	return _u
}

// AddVersionRules adds the "version_rules" edges to the VersionRule entity.
func (_u *ExamUpdateOne) AddVersionRules(v ...*VersionRule) *ExamUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionRuleIDs(ids...)
}

// Mutation returns the ExamMutation object of the builder.
func (_u *ExamUpdateOne) Mutation() *ExamMutation {
	return _u.mutation
}

// ClearSections clears all "sections" edges to the Section entity.
func (_u *ExamUpdateOne) ClearSections() *ExamUpdateOne {
	_u.mutation.ClearSections()
	return _u
}

// RemoveSectionIDs removes the "sections" edge to Section entities by IDs.
func (_u *ExamUpdateOne) RemoveSectionIDs(ids ...int) *ExamUpdateOne {
	_u.mutation.RemoveSectionIDs(ids...)
	return _u
}

// RemoveSections removes "sections" edges to Section entities.
func (_u *ExamUpdateOne) RemoveSections(v ...*Section) *ExamUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSectionIDs(ids...)
}

// ClearTopics clears all "topics" edges to the Topic entity.
func (_u *ExamUpdateOne) ClearTopics() *ExamUpdateOne {
	_u.mutation.ClearTopics()
	return _u
}

// RemoveTopicIDs removes the "topics" edge to Topic entities by IDs.
func (_u *ExamUpdateOne) RemoveTopicIDs(ids ...int) *ExamUpdateOne {
	_u.mutation.RemoveTopicIDs(ids...)
	return _u
}

// RemoveTopics removes "topics" edges to Topic entities.
func (_u *ExamUpdateOne) RemoveTopics(v ...*Topic) *ExamUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTopicIDs(ids...)
}

// ClearUnits clears all "units" edges to the Unit entity.
func (_u *ExamUpdateOne) ClearUnits() *ExamUpdateOne {
	_u.mutation.ClearUnits()
	return _u
}

// RemoveUnitIDs removes the "units" edge to Unit entities by IDs.
func (_u *ExamUpdateOne) RemoveUnitIDs(ids ...int) *ExamUpdateOne {
	_u.mutation.RemoveUnitIDs(ids...)
	return _u
}

// RemoveUnits removes "units" edges to Unit entities.
func (_u *ExamUpdateOne) RemoveUnits(v ...*Unit) *ExamUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUnitIDs(ids...)
}

// ClearVersionRules clears all "version_rules" edges to the VersionRule entity.
func (_u *ExamUpdateOne) ClearVersionRules() *ExamUpdateOne {
	_u.mutation.ClearVersionRules()
	return _u
}

// RemoveVersionRuleIDs removes the "version_rules" edge to VersionRule entities by IDs.
func (_u *ExamUpdateOne) RemoveVersionRuleIDs(ids ...int) *ExamUpdateOne {
	_u.mutation.RemoveVersionRuleIDs(ids...)
	return _u
}

// RemoveVersionRules removes "version_rules" edges to VersionRule entities.
func (_u *ExamUpdateOne) RemoveVersionRules(v ...*VersionRule) *ExamUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionRuleIDs(ids...)
}

// Where appends a list predicates to the ExamUpdate builder.
func (_u *ExamUpdateOne) Where(ps ...predicate.Exam) *ExamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExamUpdateOne) Select(field string, fields ...string) *ExamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Exam entity.
func (_u *ExamUpdateOne) Save(ctx context.Context) (*Exam, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExamUpdateOne) SaveX(ctx context.Context) *Exam {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExamUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := exam.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Exam.title": %w`, err)}
		}
	}
	return nil
}

func (_u *ExamUpdateOne) sqlSave(ctx context.Context) (_node *Exam, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(exam.Table, exam.Columns, sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Exam.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exam.FieldID)
		for _, f := range fields {
			if !exam.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != exam.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(exam.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(exam.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(exam.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.TimeLimit(); ok {
		_spec.SetField(exam.FieldTimeLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeLimit(); ok {
		_spec.AddField(exam.FieldTimeLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(exam.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.SectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.SectionsTable,
			Columns: []string{exam.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSectionsIDs(); len(nodes) > 0 && !_u.mutation.SectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.SectionsTable,
			Columns: []string{exam.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.SectionsTable,
			Columns: []string{exam.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TopicsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.TopicsTable,
			Columns: []string{exam.TopicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTopicsIDs(); len(nodes) > 0 && !_u.mutation.TopicsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.TopicsTable,
			Columns: []string{exam.TopicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TopicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.TopicsTable,
			Columns: []string{exam.TopicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.UnitsTable,
			Columns: []string{exam.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUnitsIDs(); len(nodes) > 0 && !_u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.UnitsTable,
			Columns: []string{exam.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.UnitsTable,
			Columns: []string{exam.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.VersionRulesTable,
			Columns: []string{exam.VersionRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(versionrule.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionRulesIDs(); len(nodes) > 0 && !_u.mutation.VersionRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.VersionRulesTable,
			Columns: []string{exam.VersionRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(versionrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionRulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.VersionRulesTable,
			Columns: []string{exam.VersionRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(versionrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Exam{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exam.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
