// Code generated by ent, DO NOT EDIT.

package ent

import (
	"examination/internal/ent/exam"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Exam is the model entity for the Exam schema.
type Exam struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Time limit in minutes
	TimeLimit int `json:"time_limit,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ExamQuery when eager-loading is set.
	Edges        ExamEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ExamEdges holds the relations/edges for other nodes in the graph.
type ExamEdges struct {
	// Sections holds the value of the sections edge.
	Sections []*Section `json:"sections,omitempty"`
	// Topics holds the value of the topics edge.
	Topics []*Topic `json:"topics,omitempty"`
	// Units holds the value of the units edge.
	Units []*Unit `json:"units,omitempty"`
	// VersionRules holds the value of the version_rules edge.
	VersionRules []*VersionRule `json:"version_rules,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// SectionsOrErr returns the Sections value or an error if the edge
// was not loaded in eager-loading.
func (e ExamEdges) SectionsOrErr() ([]*Section, error) {
	if e.loadedTypes[0] {
		return e.Sections, nil
	}
	return nil, &NotLoadedError{edge: "sections"}
}

// TopicsOrErr returns the Topics value or an error if the edge
// was not loaded in eager-loading.
func (e ExamEdges) TopicsOrErr() ([]*Topic, error) {
	if e.loadedTypes[1] {
		return e.Topics, nil
	}
	return nil, &NotLoadedError{edge: "topics"}
}

// UnitsOrErr returns the Units value or an error if the edge
// was not loaded in eager-loading.
func (e ExamEdges) UnitsOrErr() ([]*Unit, error) {
	if e.loadedTypes[2] {
		return e.Units, nil
	}
	return nil, &NotLoadedError{edge: "units"}
}

// VersionRulesOrErr returns the VersionRules value or an error if the edge
// was not loaded in eager-loading.
func (e ExamEdges) VersionRulesOrErr() ([]*VersionRule, error) {
	if e.loadedTypes[3] {
		return e.VersionRules, nil
	}
	return nil, &NotLoadedError{edge: "version_rules"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Exam) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case exam.FieldIsActive:
			values[i] = new(sql.NullBool)
		case exam.FieldID, exam.FieldTimeLimit:
			values[i] = new(sql.NullInt64)
		case exam.FieldTitle, exam.FieldDescription:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Exam fields.
func (_m *Exam) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case exam.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case exam.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case exam.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case exam.FieldTimeLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field time_limit", values[i])
			} else if value.Valid {
				_m.TimeLimit = int(value.Int64)
			}
		case exam.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Exam.
// This includes values selected through modifiers, order, etc.
func (_m *Exam) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySections queries the "sections" edge of the Exam entity.
func (_m *Exam) QuerySections() *SectionQuery {
	return NewExamClient(_m.config).QuerySections(_m)
}

// QueryTopics queries the "topics" edge of the Exam entity.
func (_m *Exam) QueryTopics() *TopicQuery {
	return NewExamClient(_m.config).QueryTopics(_m)
}

// QueryUnits queries the "units" edge of the Exam entity.
func (_m *Exam) QueryUnits() *UnitQuery {
	return NewExamClient(_m.config).QueryUnits(_m)
}

// QueryVersionRules queries the "version_rules" edge of the Exam entity.
func (_m *Exam) QueryVersionRules() *VersionRuleQuery {
	return NewExamClient(_m.config).QueryVersionRules(_m)
}

// Update returns a builder for updating this Exam.
// Note that you need to call Exam.Unwrap() before calling this method if this Exam
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Exam) Update() *ExamUpdateOne {
	return NewExamClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Exam entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Exam) Unwrap() *Exam {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Exam is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Exam) String() string {
	var builder strings.Builder
	builder.WriteString("Exam(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("time_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.TimeLimit))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// Exams is a parsable slice of Exam.
type Exams []*Exam
