// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"examination/internal/ent/exam"
	"examination/internal/ent/predicate"
	"examination/internal/ent/section"
	"examination/internal/ent/topic"
	"examination/internal/ent/unit"
	"examination/internal/ent/versionrule"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExamQuery is the builder for querying Exam entities.
type ExamQuery struct {
	config
	ctx              *QueryContext
	order            []exam.OrderOption
	inters           []Interceptor
	predicates       []predicate.Exam
	withSections     *SectionQuery
	withTopics       *TopicQuery
	withUnits        *UnitQuery
	withVersionRules *VersionRuleQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ExamQuery builder.
func (_q *ExamQuery) Where(ps ...predicate.Exam) *ExamQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ExamQuery) Limit(limit int) *ExamQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ExamQuery) Offset(offset int) *ExamQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ExamQuery) Unique(unique bool) *ExamQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ExamQuery) Order(o ...exam.OrderOption) *ExamQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySections chains the current query on the "sections" edge.
func (_q *ExamQuery) QuerySections() *SectionQuery {
	query := (&SectionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(exam.Table, exam.FieldID, selector),
			sqlgraph.To(section.Table, section.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, exam.SectionsTable, exam.SectionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTopics chains the current query on the "topics" edge.
func (_q *ExamQuery) QueryTopics() *TopicQuery {
	query := (&TopicClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(exam.Table, exam.FieldID, selector),
			sqlgraph.To(topic.Table, topic.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, exam.TopicsTable, exam.TopicsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUnits chains the current query on the "units" edge.
func (_q *ExamQuery) QueryUnits() *UnitQuery {
	query := (&UnitClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(exam.Table, exam.FieldID, selector),
			sqlgraph.To(unit.Table, unit.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, exam.UnitsTable, exam.UnitsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVersionRules chains the current query on the "version_rules" edge.
func (_q *ExamQuery) QueryVersionRules() *VersionRuleQuery {
	query := (&VersionRuleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(exam.Table, exam.FieldID, selector),
			sqlgraph.To(versionrule.Table, versionrule.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, exam.VersionRulesTable, exam.VersionRulesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Exam entity from the query.
// Returns a *NotFoundError when no Exam was found.
func (_q *ExamQuery) First(ctx context.Context) (*Exam, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{exam.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ExamQuery) FirstX(ctx context.Context) *Exam {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Exam ID from the query.
// Returns a *NotFoundError when no Exam ID was found.
func (_q *ExamQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{exam.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ExamQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Exam entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Exam entity is found.
// Returns a *NotFoundError when no Exam entities are found.
func (_q *ExamQuery) Only(ctx context.Context) (*Exam, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{exam.Label}
	default:
		return nil, &NotSingularError{exam.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ExamQuery) OnlyX(ctx context.Context) *Exam {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Exam ID in the query.
// Returns a *NotSingularError when more than one Exam ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ExamQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{exam.Label}
	default:
		err = &NotSingularError{exam.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ExamQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Exams.
func (_q *ExamQuery) All(ctx context.Context) ([]*Exam, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Exam, *ExamQuery]()
	return withInterceptors[[]*Exam](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ExamQuery) AllX(ctx context.Context) []*Exam {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Exam IDs.
func (_q *ExamQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(exam.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ExamQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ExamQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ExamQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ExamQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ExamQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ExamQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ExamQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ExamQuery) Clone() *ExamQuery {
	if _q == nil {
		return nil
	}
	return &ExamQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]exam.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.Exam{}, _q.predicates...),
		withSections:     _q.withSections.Clone(),
		withTopics:       _q.withTopics.Clone(),
		withUnits:        _q.withUnits.Clone(),
		withVersionRules: _q.withVersionRules.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSections tells the query-builder to eager-load the nodes that are connected to
// the "sections" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ExamQuery) WithSections(opts ...func(*SectionQuery)) *ExamQuery {
	query := (&SectionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSections = query
	return _q
}

// WithTopics tells the query-builder to eager-load the nodes that are connected to
// the "topics" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ExamQuery) WithTopics(opts ...func(*TopicQuery)) *ExamQuery {
	query := (&TopicClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTopics = query
	return _q
}

// WithUnits tells the query-builder to eager-load the nodes that are connected to
// the "units" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ExamQuery) WithUnits(opts ...func(*UnitQuery)) *ExamQuery {
	query := (&UnitClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUnits = query
	return _q
}

// WithVersionRules tells the query-builder to eager-load the nodes that are connected to
// the "version_rules" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ExamQuery) WithVersionRules(opts ...func(*VersionRuleQuery)) *ExamQuery {
	query := (&VersionRuleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVersionRules = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Exam.Query().
//		GroupBy(exam.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ExamQuery) GroupBy(field string, fields ...string) *ExamGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ExamGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = exam.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.Exam.Query().
//		Select(exam.FieldTitle).
//		Scan(ctx, &v)
func (_q *ExamQuery) Select(fields ...string) *ExamSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ExamSelect{ExamQuery: _q}
	sbuild.label = exam.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ExamSelect configured with the given aggregations.
func (_q *ExamQuery) Aggregate(fns ...AggregateFunc) *ExamSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ExamQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !exam.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ExamQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Exam, error) {
	var (
		nodes       = []*Exam{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withSections != nil,
			_q.withTopics != nil,
			_q.withUnits != nil,
			_q.withVersionRules != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Exam).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Exam{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSections; query != nil {
		if err := _q.loadSections(ctx, query, nodes,
			func(n *Exam) { n.Edges.Sections = []*Section{} },
			func(n *Exam, e *Section) { n.Edges.Sections = append(n.Edges.Sections, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTopics; query != nil {
		if err := _q.loadTopics(ctx, query, nodes,
			func(n *Exam) { n.Edges.Topics = []*Topic{} },
			func(n *Exam, e *Topic) { n.Edges.Topics = append(n.Edges.Topics, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUnits; query != nil {
		if err := _q.loadUnits(ctx, query, nodes,
			func(n *Exam) { n.Edges.Units = []*Unit{} },
			func(n *Exam, e *Unit) { n.Edges.Units = append(n.Edges.Units, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withVersionRules; query != nil {
		if err := _q.loadVersionRules(ctx, query, nodes,
			func(n *Exam) { n.Edges.VersionRules = []*VersionRule{} },
			func(n *Exam, e *VersionRule) { n.Edges.VersionRules = append(n.Edges.VersionRules, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ExamQuery) loadSections(ctx context.Context, query *SectionQuery, nodes []*Exam, init func(*Exam), assign func(*Exam, *Section)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Exam)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(section.FieldExamID)
	}
	query.Where(predicate.Section(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(exam.SectionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ExamID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "exam_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ExamQuery) loadTopics(ctx context.Context, query *TopicQuery, nodes []*Exam, init func(*Exam), assign func(*Exam, *Topic)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Exam)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(topic.FieldExamID)
	}
	query.Where(predicate.Topic(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(exam.TopicsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ExamID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "exam_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ExamQuery) loadUnits(ctx context.Context, query *UnitQuery, nodes []*Exam, init func(*Exam), assign func(*Exam, *Unit)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Exam)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(unit.FieldExamID)
	}
	query.Where(predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(exam.UnitsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ExamID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "exam_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ExamQuery) loadVersionRules(ctx context.Context, query *VersionRuleQuery, nodes []*Exam, init func(*Exam), assign func(*Exam, *VersionRule)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Exam)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(versionrule.FieldExamID)
	}
	query.Where(predicate.VersionRule(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(exam.VersionRulesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ExamID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "exam_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ExamQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ExamQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(exam.Table, exam.Columns, sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exam.FieldID)
		for i := range fields {
			if fields[i] != exam.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ExamQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(exam.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = exam.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ExamGroupBy is the group-by builder for Exam entities.
type ExamGroupBy struct {
	selector
	build *ExamQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ExamGroupBy) Aggregate(fns ...AggregateFunc) *ExamGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ExamGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExamQuery, *ExamGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ExamGroupBy) sqlScan(ctx context.Context, root *ExamQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ExamSelect is the builder for selecting fields of Exam entities.
type ExamSelect struct {
	*ExamQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ExamSelect) Aggregate(fns ...AggregateFunc) *ExamSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ExamSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExamQuery, *ExamSelect](ctx, _s.ExamQuery, _s, _s.inters, v)
}

func (_s *ExamSelect) sqlScan(ctx context.Context, root *ExamQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
