// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"examination/internal/ent/predicate"
	"examination/internal/ent/problemtranslation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProblemTranslationDelete is the builder for deleting a ProblemTranslation entity.
type ProblemTranslationDelete struct {
	config
	hooks    []Hook
	mutation *ProblemTranslationMutation
}

// Where appends a list predicates to the ProblemTranslationDelete builder.
func (_d *ProblemTranslationDelete) Where(ps ...predicate.ProblemTranslation) *ProblemTranslationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProblemTranslationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProblemTranslationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProblemTranslationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(problemtranslation.Table, sqlgraph.NewFieldSpec(problemtranslation.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProblemTranslationDeleteOne is the builder for deleting a single ProblemTranslation entity.
type ProblemTranslationDeleteOne struct {
	_d *ProblemTranslationDelete
}

// Where appends a list predicates to the ProblemTranslationDelete builder.
func (_d *ProblemTranslationDeleteOne) Where(ps ...predicate.ProblemTranslation) *ProblemTranslationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProblemTranslationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{problemtranslation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProblemTranslationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
