// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"examination/internal/ent/choice"
	"examination/internal/ent/predicate"
	"examination/internal/ent/problem"
	"examination/internal/ent/problemtranslation"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProblemTranslationUpdate is the builder for updating ProblemTranslation entities.
type ProblemTranslationUpdate struct {
	config
	hooks    []Hook
	mutation *ProblemTranslationMutation
}

// Where appends a list predicates to the ProblemTranslationUpdate builder.
func (_u *ProblemTranslationUpdate) Where(ps ...predicate.ProblemTranslation) *ProblemTranslationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLocale sets the "locale" field.
func (_u *ProblemTranslationUpdate) SetLocale(v string) *ProblemTranslationUpdate {
	_u.mutation.SetLocale(v)
	return _u
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_u *ProblemTranslationUpdate) SetNillableLocale(v *string) *ProblemTranslationUpdate {
	if v != nil {
		_u.SetLocale(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ProblemTranslationUpdate) SetTitle(v string) *ProblemTranslationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProblemTranslationUpdate) SetNillableTitle(v *string) *ProblemTranslationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ProblemTranslationUpdate) SetContent(v string) *ProblemTranslationUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ProblemTranslationUpdate) SetNillableContent(v *string) *ProblemTranslationUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetExplanation sets the "explanation" field.
func (_u *ProblemTranslationUpdate) SetExplanation(v string) *ProblemTranslationUpdate {
	_u.mutation.SetExplanation(v)
	return _u
}

// SetNillableExplanation sets the "explanation" field if the given value is not nil.
func (_u *ProblemTranslationUpdate) SetNillableExplanation(v *string) *ProblemTranslationUpdate {
	if v != nil {
		_u.SetExplanation(*v)
	}
	return _u
}

// ClearExplanation clears the value of the "explanation" field.
func (_u *ProblemTranslationUpdate) ClearExplanation() *ProblemTranslationUpdate {
	_u.mutation.ClearExplanation()
	return _u
}

// SetProblemID sets the "problem_id" field.
func (_u *ProblemTranslationUpdate) SetProblemID(v int) *ProblemTranslationUpdate {
	_u.mutation.SetProblemID(v)
	return _u
}

// SetNillableProblemID sets the "problem_id" field if the given value is not nil.
func (_u *ProblemTranslationUpdate) SetNillableProblemID(v *int) *ProblemTranslationUpdate {
	if v != nil {
		_u.SetProblemID(*v)
	}
	return _u
}

// SetProblem sets the "problem" edge to the Problem entity.
func (_u *ProblemTranslationUpdate) SetProblem(v *Problem) *ProblemTranslationUpdate {
	return _u.SetProblemID(v.ID)
}

// AddChoiceIDs adds the "choices" edge to the Choice entity by IDs.
func (_u *ProblemTranslationUpdate) AddChoiceIDs(ids ...int) *ProblemTranslationUpdate {
	_u.mutation.AddChoiceIDs(ids...)
	return _u
}

// AddChoices adds the "choices" edges to the Choice entity.
func (_u *ProblemTranslationUpdate) AddChoices(v ...*Choice) *ProblemTranslationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChoiceIDs(ids...)
}

// Mutation returns the ProblemTranslationMutation object of the builder.
func (_u *ProblemTranslationUpdate) Mutation() *ProblemTranslationMutation {
	return _u.mutation
}

// ClearProblem clears the "problem" edge to the Problem entity.
func (_u *ProblemTranslationUpdate) ClearProblem() *ProblemTranslationUpdate {
	_u.mutation.ClearProblem()
	return _u
}

// ClearChoices clears all "choices" edges to the Choice entity.
func (_u *ProblemTranslationUpdate) ClearChoices() *ProblemTranslationUpdate {
	_u.mutation.ClearChoices()
	return _u
}

// RemoveChoiceIDs removes the "choices" edge to Choice entities by IDs.
func (_u *ProblemTranslationUpdate) RemoveChoiceIDs(ids ...int) *ProblemTranslationUpdate {
	_u.mutation.RemoveChoiceIDs(ids...)
	return _u
}

// RemoveChoices removes "choices" edges to Choice entities.
func (_u *ProblemTranslationUpdate) RemoveChoices(v ...*Choice) *ProblemTranslationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChoiceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProblemTranslationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProblemTranslationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProblemTranslationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProblemTranslationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProblemTranslationUpdate) check() error {
	if v, ok := _u.mutation.Locale(); ok {
		if err := problemtranslation.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "ProblemTranslation.locale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := problemtranslation.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ProblemTranslation.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := problemtranslation.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ProblemTranslation.content": %w`, err)}
		}
	}
	if _u.mutation.ProblemCleared() && len(_u.mutation.ProblemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProblemTranslation.problem"`)
	}
	return nil
}

func (_u *ProblemTranslationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(problemtranslation.Table, problemtranslation.Columns, sqlgraph.NewFieldSpec(problemtranslation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Locale(); ok {
		_spec.SetField(problemtranslation.FieldLocale, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(problemtranslation.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(problemtranslation.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Explanation(); ok {
		_spec.SetField(problemtranslation.FieldExplanation, field.TypeString, value)
	}
	if _u.mutation.ExplanationCleared() {
		_spec.ClearField(problemtranslation.FieldExplanation, field.TypeString)
	}
	if _u.mutation.ProblemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problemtranslation.ProblemTable,
			Columns: []string{problemtranslation.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problemtranslation.ProblemTable,
			Columns: []string{problemtranslation.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemtranslation.ChoicesTable,
			Columns: []string{problemtranslation.ChoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChoicesIDs(); len(nodes) > 0 && !_u.mutation.ChoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemtranslation.ChoicesTable,
			Columns: []string{problemtranslation.ChoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemtranslation.ChoicesTable,
			Columns: []string{problemtranslation.ChoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{problemtranslation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProblemTranslationUpdateOne is the builder for updating a single ProblemTranslation entity.
type ProblemTranslationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProblemTranslationMutation
}

// SetLocale sets the "locale" field.
func (_u *ProblemTranslationUpdateOne) SetLocale(v string) *ProblemTranslationUpdateOne {
	_u.mutation.SetLocale(v)
	return _u
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_u *ProblemTranslationUpdateOne) SetNillableLocale(v *string) *ProblemTranslationUpdateOne {
	if v != nil {
		_u.SetLocale(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ProblemTranslationUpdateOne) SetTitle(v string) *ProblemTranslationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProblemTranslationUpdateOne) SetNillableTitle(v *string) *ProblemTranslationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ProblemTranslationUpdateOne) SetContent(v string) *ProblemTranslationUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ProblemTranslationUpdateOne) SetNillableContent(v *string) *ProblemTranslationUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetExplanation sets the "explanation" field.
func (_u *ProblemTranslationUpdateOne) SetExplanation(v string) *ProblemTranslationUpdateOne {
	_u.mutation.SetExplanation(v)
	return _u
}

// SetNillableExplanation sets the "explanation" field if the given value is not nil.
func (_u *ProblemTranslationUpdateOne) SetNillableExplanation(v *string) *ProblemTranslationUpdateOne {
	if v != nil {
		_u.SetExplanation(*v)
	}
	return _u
}

// ClearExplanation clears the value of the "explanation" field.
func (_u *ProblemTranslationUpdateOne) ClearExplanation() *ProblemTranslationUpdateOne {
	_u.mutation.ClearExplanation()
	return _u
}

// SetProblemID sets the "problem_id" field.
func (_u *ProblemTranslationUpdateOne) SetProblemID(v int) *ProblemTranslationUpdateOne {
	_u.mutation.SetProblemID(v)
	return _u
}

// SetNillableProblemID sets the "problem_id" field if the given value is not nil.
func (_u *ProblemTranslationUpdateOne) SetNillableProblemID(v *int) *ProblemTranslationUpdateOne {
	if v != nil {
		_u.SetProblemID(*v)
	}
	return _u
}

// SetProblem sets the "problem" edge to the Problem entity.
func (_u *ProblemTranslationUpdateOne) SetProblem(v *Problem) *ProblemTranslationUpdateOne {
	return _u.SetProblemID(v.ID)
}

// AddChoiceIDs adds the "choices" edge to the Choice entity by IDs.
func (_u *ProblemTranslationUpdateOne) AddChoiceIDs(ids ...int) *ProblemTranslationUpdateOne {
	_u.mutation.AddChoiceIDs(ids...)
	return _u
}

// AddChoices adds the "choices" edges to the Choice entity.
func (_u *ProblemTranslationUpdateOne) AddChoices(v ...*Choice) *ProblemTranslationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChoiceIDs(ids...)
}

// Mutation returns the ProblemTranslationMutation object of the builder.
func (_u *ProblemTranslationUpdateOne) Mutation() *ProblemTranslationMutation {
	return _u.mutation
}

// ClearProblem clears the "problem" edge to the Problem entity.
func (_u *ProblemTranslationUpdateOne) ClearProblem() *ProblemTranslationUpdateOne {
	_u.mutation.ClearProblem()
	return _u
}

// ClearChoices clears all "choices" edges to the Choice entity.
func (_u *ProblemTranslationUpdateOne) ClearChoices() *ProblemTranslationUpdateOne {
	_u.mutation.ClearChoices()
	return _u
}

// RemoveChoiceIDs removes the "choices" edge to Choice entities by IDs.
func (_u *ProblemTranslationUpdateOne) RemoveChoiceIDs(ids ...int) *ProblemTranslationUpdateOne {
	_u.mutation.RemoveChoiceIDs(ids...)
	return _u
}

// RemoveChoices removes "choices" edges to Choice entities.
func (_u *ProblemTranslationUpdateOne) RemoveChoices(v ...*Choice) *ProblemTranslationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChoiceIDs(ids...)
}

// Where appends a list predicates to the ProblemTranslationUpdate builder.
func (_u *ProblemTranslationUpdateOne) Where(ps ...predicate.ProblemTranslation) *ProblemTranslationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProblemTranslationUpdateOne) Select(field string, fields ...string) *ProblemTranslationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProblemTranslation entity.
func (_u *ProblemTranslationUpdateOne) Save(ctx context.Context) (*ProblemTranslation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProblemTranslationUpdateOne) SaveX(ctx context.Context) *ProblemTranslation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProblemTranslationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProblemTranslationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProblemTranslationUpdateOne) check() error {
	if v, ok := _u.mutation.Locale(); ok {
		if err := problemtranslation.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "ProblemTranslation.locale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := problemtranslation.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ProblemTranslation.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := problemtranslation.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ProblemTranslation.content": %w`, err)}
		}
	}
	if _u.mutation.ProblemCleared() && len(_u.mutation.ProblemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProblemTranslation.problem"`)
	}
	return nil
}

func (_u *ProblemTranslationUpdateOne) sqlSave(ctx context.Context) (_node *ProblemTranslation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(problemtranslation.Table, problemtranslation.Columns, sqlgraph.NewFieldSpec(problemtranslation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProblemTranslation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, problemtranslation.FieldID)
		for _, f := range fields {
			if !problemtranslation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != problemtranslation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Locale(); ok {
		_spec.SetField(problemtranslation.FieldLocale, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(problemtranslation.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(problemtranslation.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Explanation(); ok {
		_spec.SetField(problemtranslation.FieldExplanation, field.TypeString, value)
	}
	if _u.mutation.ExplanationCleared() {
		_spec.ClearField(problemtranslation.FieldExplanation, field.TypeString)
	}
	if _u.mutation.ProblemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problemtranslation.ProblemTable,
			Columns: []string{problemtranslation.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problemtranslation.ProblemTable,
			Columns: []string{problemtranslation.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemtranslation.ChoicesTable,
			Columns: []string{problemtranslation.ChoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChoicesIDs(); len(nodes) > 0 && !_u.mutation.ChoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemtranslation.ChoicesTable,
			Columns: []string{problemtranslation.ChoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemtranslation.ChoicesTable,
			Columns: []string{problemtranslation.ChoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProblemTranslation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{problemtranslation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
