// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"examination/internal/ent/problem"
	"examination/internal/ent/problemtranslation"
	"examination/internal/ent/unit"
	"examination/internal/ent/versionrule"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProblemCreate is the builder for creating a Problem entity.
type ProblemCreate struct {
	config
	mutation *ProblemMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (_c *ProblemCreate) SetType(v problem.Type) *ProblemCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ProblemCreate) SetNillableType(v *problem.Type) *ProblemCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetDifficulty sets the "difficulty" field.
func (_c *ProblemCreate) SetDifficulty(v int) *ProblemCreate {
	_c.mutation.SetDifficulty(v)
	return _c
}

// SetNillableDifficulty sets the "difficulty" field if the given value is not nil.
func (_c *ProblemCreate) SetNillableDifficulty(v *int) *ProblemCreate {
	if v != nil {
		_c.SetDifficulty(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProblemCreate) SetCreatedAt(v time.Time) *ProblemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUnitID sets the "unit_id" field.
func (_c *ProblemCreate) SetUnitID(v int) *ProblemCreate {
	_c.mutation.SetUnitID(v)
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *ProblemCreate) SetParentID(v int) *ProblemCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *ProblemCreate) SetNillableParentID(v *int) *ProblemCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetUnit sets the "unit" edge to the Unit entity.
func (_c *ProblemCreate) SetUnit(v *Unit) *ProblemCreate {
	return _c.SetUnitID(v.ID)
}

// AddVersionIDs adds the "versions" edge to the VersionRule entity by IDs.
func (_c *ProblemCreate) AddVersionIDs(ids ...int) *ProblemCreate {
	_c.mutation.AddVersionIDs(ids...)
	return _c
}

// AddVersions adds the "versions" edges to the VersionRule entity.
func (_c *ProblemCreate) AddVersions(v ...*VersionRule) *ProblemCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVersionIDs(ids...)
}

// AddTranslationIDs adds the "translations" edge to the ProblemTranslation entity by IDs.
func (_c *ProblemCreate) AddTranslationIDs(ids ...int) *ProblemCreate {
	_c.mutation.AddTranslationIDs(ids...)
	return _c
}

// AddTranslations adds the "translations" edges to the ProblemTranslation entity.
func (_c *ProblemCreate) AddTranslations(v ...*ProblemTranslation) *ProblemCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTranslationIDs(ids...)
}

// SetParent sets the "parent" edge to the Problem entity.
func (_c *ProblemCreate) SetParent(v *Problem) *ProblemCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Problem entity by IDs.
func (_c *ProblemCreate) AddChildIDs(ids ...int) *ProblemCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Problem entity.
func (_c *ProblemCreate) AddChildren(v ...*Problem) *ProblemCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// Mutation returns the ProblemMutation object of the builder.
func (_c *ProblemCreate) Mutation() *ProblemMutation {
	return _c.mutation
}

// Save creates the Problem in the database.
func (_c *ProblemCreate) Save(ctx context.Context) (*Problem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProblemCreate) SaveX(ctx context.Context) *Problem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProblemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProblemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProblemCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := problem.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Difficulty(); !ok {
		v := problem.DefaultDifficulty
		_c.mutation.SetDifficulty(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProblemCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Problem.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := problem.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Problem.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Difficulty(); !ok {
		return &ValidationError{Name: "difficulty", err: errors.New(`ent: missing required field "Problem.difficulty"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Problem.created_at"`)}
	}
	if _, ok := _c.mutation.UnitID(); !ok {
		return &ValidationError{Name: "unit_id", err: errors.New(`ent: missing required field "Problem.unit_id"`)}
	}
	if len(_c.mutation.UnitIDs()) == 0 {
		return &ValidationError{Name: "unit", err: errors.New(`ent: missing required edge "Problem.unit"`)}
	}
	return nil
}

func (_c *ProblemCreate) sqlSave(ctx context.Context) (*Problem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProblemCreate) createSpec() (*Problem, *sqlgraph.CreateSpec) {
	var (
		_node = &Problem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(problem.Table, sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(problem.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Difficulty(); ok {
		_spec.SetField(problem.FieldDifficulty, field.TypeInt, value)
		_node.Difficulty = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(problem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UnitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.UnitTable,
			Columns: []string{problem.UnitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UnitID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problem.VersionsTable,
			Columns: []string{problem.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(versionrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TranslationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problem.TranslationsTable,
			Columns: []string{problem.TranslationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problemtranslation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problem.ParentTable,
			Columns: []string{problem.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problem.ChildrenTable,
			Columns: []string{problem.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProblemCreateBulk is the builder for creating many Problem entities in bulk.
type ProblemCreateBulk struct {
	config
	err      error
	builders []*ProblemCreate
}

// Save creates the Problem entities in the database.
func (_c *ProblemCreateBulk) Save(ctx context.Context) ([]*Problem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Problem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProblemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProblemCreateBulk) SaveX(ctx context.Context) []*Problem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProblemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProblemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
