// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"examination/internal/ent/choice"
	"examination/internal/ent/predicate"
	"examination/internal/ent/problem"
	"examination/internal/ent/problemtranslation"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProblemTranslationQuery is the builder for querying ProblemTranslation entities.
type ProblemTranslationQuery struct {
	config
	ctx         *QueryContext
	order       []problemtranslation.OrderOption
	inters      []Interceptor
	predicates  []predicate.ProblemTranslation
	withProblem *ProblemQuery
	withChoices *ChoiceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProblemTranslationQuery builder.
func (_q *ProblemTranslationQuery) Where(ps ...predicate.ProblemTranslation) *ProblemTranslationQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ProblemTranslationQuery) Limit(limit int) *ProblemTranslationQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ProblemTranslationQuery) Offset(offset int) *ProblemTranslationQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ProblemTranslationQuery) Unique(unique bool) *ProblemTranslationQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ProblemTranslationQuery) Order(o ...problemtranslation.OrderOption) *ProblemTranslationQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProblem chains the current query on the "problem" edge.
func (_q *ProblemTranslationQuery) QueryProblem() *ProblemQuery {
	query := (&ProblemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(problemtranslation.Table, problemtranslation.FieldID, selector),
			sqlgraph.To(problem.Table, problem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, problemtranslation.ProblemTable, problemtranslation.ProblemColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChoices chains the current query on the "choices" edge.
func (_q *ProblemTranslationQuery) QueryChoices() *ChoiceQuery {
	query := (&ChoiceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(problemtranslation.Table, problemtranslation.FieldID, selector),
			sqlgraph.To(choice.Table, choice.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, problemtranslation.ChoicesTable, problemtranslation.ChoicesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProblemTranslation entity from the query.
// Returns a *NotFoundError when no ProblemTranslation was found.
func (_q *ProblemTranslationQuery) First(ctx context.Context) (*ProblemTranslation, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{problemtranslation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ProblemTranslationQuery) FirstX(ctx context.Context) *ProblemTranslation {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProblemTranslation ID from the query.
// Returns a *NotFoundError when no ProblemTranslation ID was found.
func (_q *ProblemTranslationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{problemtranslation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ProblemTranslationQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProblemTranslation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProblemTranslation entity is found.
// Returns a *NotFoundError when no ProblemTranslation entities are found.
func (_q *ProblemTranslationQuery) Only(ctx context.Context) (*ProblemTranslation, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{problemtranslation.Label}
	default:
		return nil, &NotSingularError{problemtranslation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ProblemTranslationQuery) OnlyX(ctx context.Context) *ProblemTranslation {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProblemTranslation ID in the query.
// Returns a *NotSingularError when more than one ProblemTranslation ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ProblemTranslationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{problemtranslation.Label}
	default:
		err = &NotSingularError{problemtranslation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ProblemTranslationQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProblemTranslations.
func (_q *ProblemTranslationQuery) All(ctx context.Context) ([]*ProblemTranslation, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProblemTranslation, *ProblemTranslationQuery]()
	return withInterceptors[[]*ProblemTranslation](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ProblemTranslationQuery) AllX(ctx context.Context) []*ProblemTranslation {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProblemTranslation IDs.
func (_q *ProblemTranslationQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(problemtranslation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ProblemTranslationQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ProblemTranslationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ProblemTranslationQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ProblemTranslationQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ProblemTranslationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ProblemTranslationQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProblemTranslationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ProblemTranslationQuery) Clone() *ProblemTranslationQuery {
	if _q == nil {
		return nil
	}
	return &ProblemTranslationQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]problemtranslation.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.ProblemTranslation{}, _q.predicates...),
		withProblem: _q.withProblem.Clone(),
		withChoices: _q.withChoices.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProblem tells the query-builder to eager-load the nodes that are connected to
// the "problem" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProblemTranslationQuery) WithProblem(opts ...func(*ProblemQuery)) *ProblemTranslationQuery {
	query := (&ProblemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProblem = query
	return _q
}

// WithChoices tells the query-builder to eager-load the nodes that are connected to
// the "choices" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProblemTranslationQuery) WithChoices(opts ...func(*ChoiceQuery)) *ProblemTranslationQuery {
	query := (&ChoiceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChoices = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Locale string `json:"locale,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProblemTranslation.Query().
//		GroupBy(problemtranslation.FieldLocale).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ProblemTranslationQuery) GroupBy(field string, fields ...string) *ProblemTranslationGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProblemTranslationGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = problemtranslation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Locale string `json:"locale,omitempty"`
//	}
//
//	client.ProblemTranslation.Query().
//		Select(problemtranslation.FieldLocale).
//		Scan(ctx, &v)
func (_q *ProblemTranslationQuery) Select(fields ...string) *ProblemTranslationSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ProblemTranslationSelect{ProblemTranslationQuery: _q}
	sbuild.label = problemtranslation.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProblemTranslationSelect configured with the given aggregations.
func (_q *ProblemTranslationQuery) Aggregate(fns ...AggregateFunc) *ProblemTranslationSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ProblemTranslationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !problemtranslation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ProblemTranslationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProblemTranslation, error) {
	var (
		nodes       = []*ProblemTranslation{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withProblem != nil,
			_q.withChoices != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProblemTranslation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProblemTranslation{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProblem; query != nil {
		if err := _q.loadProblem(ctx, query, nodes, nil,
			func(n *ProblemTranslation, e *Problem) { n.Edges.Problem = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChoices; query != nil {
		if err := _q.loadChoices(ctx, query, nodes,
			func(n *ProblemTranslation) { n.Edges.Choices = []*Choice{} },
			func(n *ProblemTranslation, e *Choice) { n.Edges.Choices = append(n.Edges.Choices, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ProblemTranslationQuery) loadProblem(ctx context.Context, query *ProblemQuery, nodes []*ProblemTranslation, init func(*ProblemTranslation), assign func(*ProblemTranslation, *Problem)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ProblemTranslation)
	for i := range nodes {
		fk := nodes[i].ProblemID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(problem.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "problem_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProblemTranslationQuery) loadChoices(ctx context.Context, query *ChoiceQuery, nodes []*ProblemTranslation, init func(*ProblemTranslation), assign func(*ProblemTranslation, *Choice)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ProblemTranslation)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(choice.FieldProblemTranslationID)
	}
	query.Where(predicate.Choice(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(problemtranslation.ChoicesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProblemTranslationID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "problem_translation_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ProblemTranslationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ProblemTranslationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(problemtranslation.Table, problemtranslation.Columns, sqlgraph.NewFieldSpec(problemtranslation.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, problemtranslation.FieldID)
		for i := range fields {
			if fields[i] != problemtranslation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProblem != nil {
			_spec.Node.AddColumnOnce(problemtranslation.FieldProblemID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ProblemTranslationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(problemtranslation.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = problemtranslation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProblemTranslationGroupBy is the group-by builder for ProblemTranslation entities.
type ProblemTranslationGroupBy struct {
	selector
	build *ProblemTranslationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ProblemTranslationGroupBy) Aggregate(fns ...AggregateFunc) *ProblemTranslationGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ProblemTranslationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProblemTranslationQuery, *ProblemTranslationGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ProblemTranslationGroupBy) sqlScan(ctx context.Context, root *ProblemTranslationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProblemTranslationSelect is the builder for selecting fields of ProblemTranslation entities.
type ProblemTranslationSelect struct {
	*ProblemTranslationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ProblemTranslationSelect) Aggregate(fns ...AggregateFunc) *ProblemTranslationSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ProblemTranslationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProblemTranslationQuery, *ProblemTranslationSelect](ctx, _s.ProblemTranslationQuery, _s, _s.inters, v)
}

func (_s *ProblemTranslationSelect) sqlScan(ctx context.Context, root *ProblemTranslationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
