// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"examination/internal/ent/choice"
	"examination/internal/ent/problem"
	"examination/internal/ent/problemtranslation"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProblemTranslationCreate is the builder for creating a ProblemTranslation entity.
type ProblemTranslationCreate struct {
	config
	mutation *ProblemTranslationMutation
	hooks    []Hook
}

// SetLocale sets the "locale" field.
func (_c *ProblemTranslationCreate) SetLocale(v string) *ProblemTranslationCreate {
	_c.mutation.SetLocale(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ProblemTranslationCreate) SetTitle(v string) *ProblemTranslationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ProblemTranslationCreate) SetContent(v string) *ProblemTranslationCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetExplanation sets the "explanation" field.
func (_c *ProblemTranslationCreate) SetExplanation(v string) *ProblemTranslationCreate {
	_c.mutation.SetExplanation(v)
	return _c
}

// SetNillableExplanation sets the "explanation" field if the given value is not nil.
func (_c *ProblemTranslationCreate) SetNillableExplanation(v *string) *ProblemTranslationCreate {
	if v != nil {
		_c.SetExplanation(*v)
	}
	return _c
}

// SetProblemID sets the "problem_id" field.
func (_c *ProblemTranslationCreate) SetProblemID(v int) *ProblemTranslationCreate {
	_c.mutation.SetProblemID(v)
	return _c
}

// SetProblem sets the "problem" edge to the Problem entity.
func (_c *ProblemTranslationCreate) SetProblem(v *Problem) *ProblemTranslationCreate {
	return _c.SetProblemID(v.ID)
}

// AddChoiceIDs adds the "choices" edge to the Choice entity by IDs.
func (_c *ProblemTranslationCreate) AddChoiceIDs(ids ...int) *ProblemTranslationCreate {
	_c.mutation.AddChoiceIDs(ids...)
	return _c
}

// AddChoices adds the "choices" edges to the Choice entity.
func (_c *ProblemTranslationCreate) AddChoices(v ...*Choice) *ProblemTranslationCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChoiceIDs(ids...)
}

// Mutation returns the ProblemTranslationMutation object of the builder.
func (_c *ProblemTranslationCreate) Mutation() *ProblemTranslationMutation {
	return _c.mutation
}

// Save creates the ProblemTranslation in the database.
func (_c *ProblemTranslationCreate) Save(ctx context.Context) (*ProblemTranslation, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProblemTranslationCreate) SaveX(ctx context.Context) *ProblemTranslation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProblemTranslationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProblemTranslationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProblemTranslationCreate) check() error {
	if _, ok := _c.mutation.Locale(); !ok {
		return &ValidationError{Name: "locale", err: errors.New(`ent: missing required field "ProblemTranslation.locale"`)}
	}
	if v, ok := _c.mutation.Locale(); ok {
		if err := problemtranslation.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "ProblemTranslation.locale": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ProblemTranslation.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := problemtranslation.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ProblemTranslation.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "ProblemTranslation.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := problemtranslation.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ProblemTranslation.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProblemID(); !ok {
		return &ValidationError{Name: "problem_id", err: errors.New(`ent: missing required field "ProblemTranslation.problem_id"`)}
	}
	if len(_c.mutation.ProblemIDs()) == 0 {
		return &ValidationError{Name: "problem", err: errors.New(`ent: missing required edge "ProblemTranslation.problem"`)}
	}
	return nil
}

func (_c *ProblemTranslationCreate) sqlSave(ctx context.Context) (*ProblemTranslation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProblemTranslationCreate) createSpec() (*ProblemTranslation, *sqlgraph.CreateSpec) {
	var (
		_node = &ProblemTranslation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(problemtranslation.Table, sqlgraph.NewFieldSpec(problemtranslation.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Locale(); ok {
		_spec.SetField(problemtranslation.FieldLocale, field.TypeString, value)
		_node.Locale = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(problemtranslation.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(problemtranslation.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Explanation(); ok {
		_spec.SetField(problemtranslation.FieldExplanation, field.TypeString, value)
		_node.Explanation = value
	}
	if nodes := _c.mutation.ProblemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problemtranslation.ProblemTable,
			Columns: []string{problemtranslation.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProblemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemtranslation.ChoicesTable,
			Columns: []string{problemtranslation.ChoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProblemTranslationCreateBulk is the builder for creating many ProblemTranslation entities in bulk.
type ProblemTranslationCreateBulk struct {
	config
	err      error
	builders []*ProblemTranslationCreate
}

// Save creates the ProblemTranslation entities in the database.
func (_c *ProblemTranslationCreateBulk) Save(ctx context.Context) ([]*ProblemTranslation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProblemTranslation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProblemTranslationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProblemTranslationCreateBulk) SaveX(ctx context.Context) []*ProblemTranslation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProblemTranslationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProblemTranslationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
