// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"examination/internal/ent/exam"
	"examination/internal/ent/predicate"
	"examination/internal/ent/section"
	"examination/internal/ent/topic"
	"examination/internal/ent/unit"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SectionUpdate is the builder for updating Section entities.
type SectionUpdate struct {
	config
	hooks    []Hook
	mutation *SectionMutation
}

// Where appends a list predicates to the SectionUpdate builder.
func (_u *SectionUpdate) Where(ps ...predicate.Section) *SectionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *SectionUpdate) SetTitle(v string) *SectionUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SectionUpdate) SetNillableTitle(v *string) *SectionUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSeq sets the "seq" field.
func (_u *SectionUpdate) SetSeq(v int) *SectionUpdate {
	_u.mutation.ResetSeq()
	_u.mutation.SetSeq(v)
	return _u
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_u *SectionUpdate) SetNillableSeq(v *int) *SectionUpdate {
	if v != nil {
		_u.SetSeq(*v)
	}
	return _u
}

// AddSeq adds value to the "seq" field.
func (_u *SectionUpdate) AddSeq(v int) *SectionUpdate {
	_u.mutation.AddSeq(v)
	return _u
}

// SetExamID sets the "exam_id" field.
func (_u *SectionUpdate) SetExamID(v int) *SectionUpdate {
	_u.mutation.SetExamID(v)
	return _u
}

// SetNillableExamID sets the "exam_id" field if the given value is not nil.
func (_u *SectionUpdate) SetNillableExamID(v *int) *SectionUpdate {
	if v != nil {
		_u.SetExamID(*v)
	}
	return _u
}

// SetExam sets the "exam" edge to the Exam entity.
func (_u *SectionUpdate) SetExam(v *Exam) *SectionUpdate {
	return _u.SetExamID(v.ID)
}

// AddTopicIDs adds the "topics" edge to the Topic entity by IDs.
func (_u *SectionUpdate) AddTopicIDs(ids ...int) *SectionUpdate {
	_u.mutation.AddTopicIDs(ids...)
	return _u
}

// AddTopics adds the "topics" edges to the Topic entity.
func (_u *SectionUpdate) AddTopics(v ...*Topic) *SectionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTopicIDs(ids...)
}

// AddUnitIDs adds the "units" edge to the Unit entity by IDs.
func (_u *SectionUpdate) AddUnitIDs(ids ...int) *SectionUpdate {
	_u.mutation.AddUnitIDs(ids...)
	return _u
}

// AddUnits adds the "units" edges to the Unit entity.
func (_u *SectionUpdate) AddUnits(v ...*Unit) *SectionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUnitIDs(ids...)
}

// Mutation returns the SectionMutation object of the builder.
func (_u *SectionUpdate) Mutation() *SectionMutation {
	return _u.mutation
}

// ClearExam clears the "exam" edge to the Exam entity.
func (_u *SectionUpdate) ClearExam() *SectionUpdate {
	_u.mutation.ClearExam()
	return _u
}

// ClearTopics clears all "topics" edges to the Topic entity.
func (_u *SectionUpdate) ClearTopics() *SectionUpdate {
	_u.mutation.ClearTopics()
	return _u
}

// RemoveTopicIDs removes the "topics" edge to Topic entities by IDs.
func (_u *SectionUpdate) RemoveTopicIDs(ids ...int) *SectionUpdate {
	_u.mutation.RemoveTopicIDs(ids...)
	return _u
}

// RemoveTopics removes "topics" edges to Topic entities.
func (_u *SectionUpdate) RemoveTopics(v ...*Topic) *SectionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTopicIDs(ids...)
}

// ClearUnits clears all "units" edges to the Unit entity.
func (_u *SectionUpdate) ClearUnits() *SectionUpdate {
	_u.mutation.ClearUnits()
	return _u
}

// RemoveUnitIDs removes the "units" edge to Unit entities by IDs.
func (_u *SectionUpdate) RemoveUnitIDs(ids ...int) *SectionUpdate {
	_u.mutation.RemoveUnitIDs(ids...)
	return _u
}

// RemoveUnits removes "units" edges to Unit entities.
func (_u *SectionUpdate) RemoveUnits(v ...*Unit) *SectionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUnitIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SectionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SectionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SectionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SectionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SectionUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := section.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Section.title": %w`, err)}
		}
	}
	if _u.mutation.ExamCleared() && len(_u.mutation.ExamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Section.exam"`)
	}
	return nil
}

func (_u *SectionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(section.Table, section.Columns, sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(section.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Seq(); ok {
		_spec.SetField(section.FieldSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeq(); ok {
		_spec.AddField(section.FieldSeq, field.TypeInt, value)
	}
	if _u.mutation.ExamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   section.ExamTable,
			Columns: []string{section.ExamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   section.ExamTable,
			Columns: []string{section.ExamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TopicsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.TopicsTable,
			Columns: []string{section.TopicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTopicsIDs(); len(nodes) > 0 && !_u.mutation.TopicsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.TopicsTable,
			Columns: []string{section.TopicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TopicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.TopicsTable,
			Columns: []string{section.TopicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.UnitsTable,
			Columns: []string{section.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUnitsIDs(); len(nodes) > 0 && !_u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.UnitsTable,
			Columns: []string{section.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.UnitsTable,
			Columns: []string{section.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{section.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SectionUpdateOne is the builder for updating a single Section entity.
type SectionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SectionMutation
}

// SetTitle sets the "title" field.
func (_u *SectionUpdateOne) SetTitle(v string) *SectionUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SectionUpdateOne) SetNillableTitle(v *string) *SectionUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSeq sets the "seq" field.
func (_u *SectionUpdateOne) SetSeq(v int) *SectionUpdateOne {
	_u.mutation.ResetSeq()
	_u.mutation.SetSeq(v)
	return _u
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_u *SectionUpdateOne) SetNillableSeq(v *int) *SectionUpdateOne {
	if v != nil {
		_u.SetSeq(*v)
	}
	return _u
}

// AddSeq adds value to the "seq" field.
func (_u *SectionUpdateOne) AddSeq(v int) *SectionUpdateOne {
	_u.mutation.AddSeq(v)
	return _u
}

// SetExamID sets the "exam_id" field.
func (_u *SectionUpdateOne) SetExamID(v int) *SectionUpdateOne {
	_u.mutation.SetExamID(v)
	return _u
}

// SetNillableExamID sets the "exam_id" field if the given value is not nil.
func (_u *SectionUpdateOne) SetNillableExamID(v *int) *SectionUpdateOne {
	if v != nil {
		_u.SetExamID(*v)
	}
	return _u
}

// SetExam sets the "exam" edge to the Exam entity.
func (_u *SectionUpdateOne) SetExam(v *Exam) *SectionUpdateOne {
	return _u.SetExamID(v.ID)
}

// AddTopicIDs adds the "topics" edge to the Topic entity by IDs.
func (_u *SectionUpdateOne) AddTopicIDs(ids ...int) *SectionUpdateOne {
	_u.mutation.AddTopicIDs(ids...)
	return _u
}

// AddTopics adds the "topics" edges to the Topic entity.
func (_u *SectionUpdateOne) AddTopics(v ...*Topic) *SectionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTopicIDs(ids...)
}

// AddUnitIDs adds the "units" edge to the Unit entity by IDs.
func (_u *SectionUpdateOne) AddUnitIDs(ids ...int) *SectionUpdateOne {
	_u.mutation.AddUnitIDs(ids...)
	return _u
}

// AddUnits adds the "units" edges to the Unit entity.
func (_u *SectionUpdateOne) AddUnits(v ...*Unit) *SectionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUnitIDs(ids...)
}

// Mutation returns the SectionMutation object of the builder.
func (_u *SectionUpdateOne) Mutation() *SectionMutation {
	return _u.mutation
}

// ClearExam clears the "exam" edge to the Exam entity.
func (_u *SectionUpdateOne) ClearExam() *SectionUpdateOne {
	_u.mutation.ClearExam()
	return _u
}

// ClearTopics clears all "topics" edges to the Topic entity.
func (_u *SectionUpdateOne) ClearTopics() *SectionUpdateOne {
	_u.mutation.ClearTopics()
	return _u
}

// RemoveTopicIDs removes the "topics" edge to Topic entities by IDs.
func (_u *SectionUpdateOne) RemoveTopicIDs(ids ...int) *SectionUpdateOne {
	_u.mutation.RemoveTopicIDs(ids...)
	return _u
}

// RemoveTopics removes "topics" edges to Topic entities.
func (_u *SectionUpdateOne) RemoveTopics(v ...*Topic) *SectionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTopicIDs(ids...)
}

// ClearUnits clears all "units" edges to the Unit entity.
func (_u *SectionUpdateOne) ClearUnits() *SectionUpdateOne {
	_u.mutation.ClearUnits()
	return _u
}

// RemoveUnitIDs removes the "units" edge to Unit entities by IDs.
func (_u *SectionUpdateOne) RemoveUnitIDs(ids ...int) *SectionUpdateOne {
	_u.mutation.RemoveUnitIDs(ids...)
	return _u
}

// RemoveUnits removes "units" edges to Unit entities.
func (_u *SectionUpdateOne) RemoveUnits(v ...*Unit) *SectionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUnitIDs(ids...)
}

// Where appends a list predicates to the SectionUpdate builder.
func (_u *SectionUpdateOne) Where(ps ...predicate.Section) *SectionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SectionUpdateOne) Select(field string, fields ...string) *SectionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Section entity.
func (_u *SectionUpdateOne) Save(ctx context.Context) (*Section, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SectionUpdateOne) SaveX(ctx context.Context) *Section {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SectionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SectionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SectionUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := section.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Section.title": %w`, err)}
		}
	}
	if _u.mutation.ExamCleared() && len(_u.mutation.ExamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Section.exam"`)
	}
	return nil
}

func (_u *SectionUpdateOne) sqlSave(ctx context.Context) (_node *Section, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(section.Table, section.Columns, sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Section.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, section.FieldID)
		for _, f := range fields {
			if !section.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != section.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(section.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Seq(); ok {
		_spec.SetField(section.FieldSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeq(); ok {
		_spec.AddField(section.FieldSeq, field.TypeInt, value)
	}
	if _u.mutation.ExamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   section.ExamTable,
			Columns: []string{section.ExamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   section.ExamTable,
			Columns: []string{section.ExamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TopicsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.TopicsTable,
			Columns: []string{section.TopicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTopicsIDs(); len(nodes) > 0 && !_u.mutation.TopicsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.TopicsTable,
			Columns: []string{section.TopicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TopicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.TopicsTable,
			Columns: []string{section.TopicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.UnitsTable,
			Columns: []string{section.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUnitsIDs(); len(nodes) > 0 && !_u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.UnitsTable,
			Columns: []string{section.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.UnitsTable,
			Columns: []string{section.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Section{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{section.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
