// Code generated by ent, DO NOT EDIT.

package ent

import (
	"examination/internal/ent/exam"
	"examination/internal/ent/section"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Section is the model entity for the Section schema.
type Section struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Sequence order
	Seq int `json:"seq,omitempty"`
	// ExamID holds the value of the "exam_id" field.
	ExamID int `json:"exam_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SectionQuery when eager-loading is set.
	Edges        SectionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SectionEdges holds the relations/edges for other nodes in the graph.
type SectionEdges struct {
	// Exam holds the value of the exam edge.
	Exam *Exam `json:"exam,omitempty"`
	// Topics holds the value of the topics edge.
	Topics []*Topic `json:"topics,omitempty"`
	// Units holds the value of the units edge.
	Units []*Unit `json:"units,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ExamOrErr returns the Exam value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SectionEdges) ExamOrErr() (*Exam, error) {
	if e.Exam != nil {
		return e.Exam, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: exam.Label}
	}
	return nil, &NotLoadedError{edge: "exam"}
}

// TopicsOrErr returns the Topics value or an error if the edge
// was not loaded in eager-loading.
func (e SectionEdges) TopicsOrErr() ([]*Topic, error) {
	if e.loadedTypes[1] {
		return e.Topics, nil
	}
	return nil, &NotLoadedError{edge: "topics"}
}

// UnitsOrErr returns the Units value or an error if the edge
// was not loaded in eager-loading.
func (e SectionEdges) UnitsOrErr() ([]*Unit, error) {
	if e.loadedTypes[2] {
		return e.Units, nil
	}
	return nil, &NotLoadedError{edge: "units"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Section) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case section.FieldID, section.FieldSeq, section.FieldExamID:
			values[i] = new(sql.NullInt64)
		case section.FieldTitle:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Section fields.
func (_m *Section) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case section.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case section.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case section.FieldSeq:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field seq", values[i])
			} else if value.Valid {
				_m.Seq = int(value.Int64)
			}
		case section.FieldExamID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field exam_id", values[i])
			} else if value.Valid {
				_m.ExamID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Section.
// This includes values selected through modifiers, order, etc.
func (_m *Section) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryExam queries the "exam" edge of the Section entity.
func (_m *Section) QueryExam() *ExamQuery {
	return NewSectionClient(_m.config).QueryExam(_m)
}

// QueryTopics queries the "topics" edge of the Section entity.
func (_m *Section) QueryTopics() *TopicQuery {
	return NewSectionClient(_m.config).QueryTopics(_m)
}

// QueryUnits queries the "units" edge of the Section entity.
func (_m *Section) QueryUnits() *UnitQuery {
	return NewSectionClient(_m.config).QueryUnits(_m)
}

// Update returns a builder for updating this Section.
// Note that you need to call Section.Unwrap() before calling this method if this Section
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Section) Update() *SectionUpdateOne {
	return NewSectionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Section entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Section) Unwrap() *Section {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Section is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Section) String() string {
	var builder strings.Builder
	builder.WriteString("Section(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("seq=")
	builder.WriteString(fmt.Sprintf("%v", _m.Seq))
	builder.WriteString(", ")
	builder.WriteString("exam_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExamID))
	builder.WriteByte(')')
	return builder.String()
}

// Sections is a parsable slice of Section.
type Sections []*Section
