// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"examination/internal/ent/exam"
	"examination/internal/ent/section"
	"examination/internal/ent/topic"
	"examination/internal/ent/unit"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SectionCreate is the builder for creating a Section entity.
type SectionCreate struct {
	config
	mutation *SectionMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *SectionCreate) SetTitle(v string) *SectionCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSeq sets the "seq" field.
func (_c *SectionCreate) SetSeq(v int) *SectionCreate {
	_c.mutation.SetSeq(v)
	return _c
}

// SetExamID sets the "exam_id" field.
func (_c *SectionCreate) SetExamID(v int) *SectionCreate {
	_c.mutation.SetExamID(v)
	return _c
}

// SetExam sets the "exam" edge to the Exam entity.
func (_c *SectionCreate) SetExam(v *Exam) *SectionCreate {
	return _c.SetExamID(v.ID)
}

// AddTopicIDs adds the "topics" edge to the Topic entity by IDs.
func (_c *SectionCreate) AddTopicIDs(ids ...int) *SectionCreate {
	_c.mutation.AddTopicIDs(ids...)
	return _c
}

// AddTopics adds the "topics" edges to the Topic entity.
func (_c *SectionCreate) AddTopics(v ...*Topic) *SectionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTopicIDs(ids...)
}

// AddUnitIDs adds the "units" edge to the Unit entity by IDs.
func (_c *SectionCreate) AddUnitIDs(ids ...int) *SectionCreate {
	_c.mutation.AddUnitIDs(ids...)
	return _c
}

// AddUnits adds the "units" edges to the Unit entity.
func (_c *SectionCreate) AddUnits(v ...*Unit) *SectionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUnitIDs(ids...)
}

// Mutation returns the SectionMutation object of the builder.
func (_c *SectionCreate) Mutation() *SectionMutation {
	return _c.mutation
}

// Save creates the Section in the database.
func (_c *SectionCreate) Save(ctx context.Context) (*Section, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SectionCreate) SaveX(ctx context.Context) *Section {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SectionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SectionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SectionCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Section.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := section.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Section.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Seq(); !ok {
		return &ValidationError{Name: "seq", err: errors.New(`ent: missing required field "Section.seq"`)}
	}
	if _, ok := _c.mutation.ExamID(); !ok {
		return &ValidationError{Name: "exam_id", err: errors.New(`ent: missing required field "Section.exam_id"`)}
	}
	if len(_c.mutation.ExamIDs()) == 0 {
		return &ValidationError{Name: "exam", err: errors.New(`ent: missing required edge "Section.exam"`)}
	}
	return nil
}

func (_c *SectionCreate) sqlSave(ctx context.Context) (*Section, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SectionCreate) createSpec() (*Section, *sqlgraph.CreateSpec) {
	var (
		_node = &Section{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(section.Table, sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(section.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Seq(); ok {
		_spec.SetField(section.FieldSeq, field.TypeInt, value)
		_node.Seq = value
	}
	if nodes := _c.mutation.ExamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   section.ExamTable,
			Columns: []string{section.ExamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ExamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TopicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.TopicsTable,
			Columns: []string{section.TopicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.UnitsTable,
			Columns: []string{section.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SectionCreateBulk is the builder for creating many Section entities in bulk.
type SectionCreateBulk struct {
	config
	err      error
	builders []*SectionCreate
}

// Save creates the Section entities in the database.
func (_c *SectionCreateBulk) Save(ctx context.Context) ([]*Section, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Section, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SectionCreateBulk) SaveX(ctx context.Context) []*Section {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SectionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SectionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
