// Code generated by ent, DO NOT EDIT.

package ent

import (
	"examination/internal/ent/exam"
	"examination/internal/ent/section"
	"examination/internal/ent/topic"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Topic is the model entity for the Topic schema.
type Topic struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Sequence order
	Seq int `json:"seq,omitempty"`
	// ExamID holds the value of the "exam_id" field.
	ExamID int `json:"exam_id,omitempty"`
	// SectionID holds the value of the "section_id" field.
	SectionID *int `json:"section_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TopicQuery when eager-loading is set.
	Edges        TopicEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TopicEdges holds the relations/edges for other nodes in the graph.
type TopicEdges struct {
	// Exam holds the value of the exam edge.
	Exam *Exam `json:"exam,omitempty"`
	// Section holds the value of the section edge.
	Section *Section `json:"section,omitempty"`
	// Units holds the value of the units edge.
	Units []*Unit `json:"units,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ExamOrErr returns the Exam value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TopicEdges) ExamOrErr() (*Exam, error) {
	if e.Exam != nil {
		return e.Exam, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: exam.Label}
	}
	return nil, &NotLoadedError{edge: "exam"}
}

// SectionOrErr returns the Section value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TopicEdges) SectionOrErr() (*Section, error) {
	if e.Section != nil {
		return e.Section, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: section.Label}
	}
	return nil, &NotLoadedError{edge: "section"}
}

// UnitsOrErr returns the Units value or an error if the edge
// was not loaded in eager-loading.
func (e TopicEdges) UnitsOrErr() ([]*Unit, error) {
	if e.loadedTypes[2] {
		return e.Units, nil
	}
	return nil, &NotLoadedError{edge: "units"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Topic) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case topic.FieldID, topic.FieldSeq, topic.FieldExamID, topic.FieldSectionID:
			values[i] = new(sql.NullInt64)
		case topic.FieldTitle:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Topic fields.
func (_m *Topic) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case topic.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case topic.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case topic.FieldSeq:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field seq", values[i])
			} else if value.Valid {
				_m.Seq = int(value.Int64)
			}
		case topic.FieldExamID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field exam_id", values[i])
			} else if value.Valid {
				_m.ExamID = int(value.Int64)
			}
		case topic.FieldSectionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field section_id", values[i])
			} else if value.Valid {
				_m.SectionID = new(int)
				*_m.SectionID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Topic.
// This includes values selected through modifiers, order, etc.
func (_m *Topic) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryExam queries the "exam" edge of the Topic entity.
func (_m *Topic) QueryExam() *ExamQuery {
	return NewTopicClient(_m.config).QueryExam(_m)
}

// QuerySection queries the "section" edge of the Topic entity.
func (_m *Topic) QuerySection() *SectionQuery {
	return NewTopicClient(_m.config).QuerySection(_m)
}

// QueryUnits queries the "units" edge of the Topic entity.
func (_m *Topic) QueryUnits() *UnitQuery {
	return NewTopicClient(_m.config).QueryUnits(_m)
}

// Update returns a builder for updating this Topic.
// Note that you need to call Topic.Unwrap() before calling this method if this Topic
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Topic) Update() *TopicUpdateOne {
	return NewTopicClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Topic entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Topic) Unwrap() *Topic {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Topic is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Topic) String() string {
	var builder strings.Builder
	builder.WriteString("Topic(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("seq=")
	builder.WriteString(fmt.Sprintf("%v", _m.Seq))
	builder.WriteString(", ")
	builder.WriteString("exam_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExamID))
	builder.WriteString(", ")
	if v := _m.SectionID; v != nil {
		builder.WriteString("section_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Topics is a parsable slice of Topic.
type Topics []*Topic
