// Code generated by ent, DO NOT EDIT.

package ent

import (
	"examination/internal/ent/exam"
	"examination/internal/ent/section"
	"examination/internal/ent/topic"
	"examination/internal/ent/unit"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Unit is the model entity for the Unit schema.
type Unit struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Sequence order
	Seq int `json:"seq,omitempty"`
	// ExamID holds the value of the "exam_id" field.
	ExamID int `json:"exam_id,omitempty"`
	// SectionID holds the value of the "section_id" field.
	SectionID *int `json:"section_id,omitempty"`
	// TopicID holds the value of the "topic_id" field.
	TopicID *int `json:"topic_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UnitQuery when eager-loading is set.
	Edges        UnitEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UnitEdges holds the relations/edges for other nodes in the graph.
type UnitEdges struct {
	// Exam holds the value of the exam edge.
	Exam *Exam `json:"exam,omitempty"`
	// Section holds the value of the section edge.
	Section *Section `json:"section,omitempty"`
	// Topic holds the value of the topic edge.
	Topic *Topic `json:"topic,omitempty"`
	// Problems holds the value of the problems edge.
	Problems []*Problem `json:"problems,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// ExamOrErr returns the Exam value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UnitEdges) ExamOrErr() (*Exam, error) {
	if e.Exam != nil {
		return e.Exam, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: exam.Label}
	}
	return nil, &NotLoadedError{edge: "exam"}
}

// SectionOrErr returns the Section value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UnitEdges) SectionOrErr() (*Section, error) {
	if e.Section != nil {
		return e.Section, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: section.Label}
	}
	return nil, &NotLoadedError{edge: "section"}
}

// TopicOrErr returns the Topic value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UnitEdges) TopicOrErr() (*Topic, error) {
	if e.Topic != nil {
		return e.Topic, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: topic.Label}
	}
	return nil, &NotLoadedError{edge: "topic"}
}

// ProblemsOrErr returns the Problems value or an error if the edge
// was not loaded in eager-loading.
func (e UnitEdges) ProblemsOrErr() ([]*Problem, error) {
	if e.loadedTypes[3] {
		return e.Problems, nil
	}
	return nil, &NotLoadedError{edge: "problems"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Unit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case unit.FieldID, unit.FieldSeq, unit.FieldExamID, unit.FieldSectionID, unit.FieldTopicID:
			values[i] = new(sql.NullInt64)
		case unit.FieldTitle:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Unit fields.
func (_m *Unit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case unit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case unit.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case unit.FieldSeq:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field seq", values[i])
			} else if value.Valid {
				_m.Seq = int(value.Int64)
			}
		case unit.FieldExamID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field exam_id", values[i])
			} else if value.Valid {
				_m.ExamID = int(value.Int64)
			}
		case unit.FieldSectionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field section_id", values[i])
			} else if value.Valid {
				_m.SectionID = new(int)
				*_m.SectionID = int(value.Int64)
			}
		case unit.FieldTopicID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field topic_id", values[i])
			} else if value.Valid {
				_m.TopicID = new(int)
				*_m.TopicID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Unit.
// This includes values selected through modifiers, order, etc.
func (_m *Unit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryExam queries the "exam" edge of the Unit entity.
func (_m *Unit) QueryExam() *ExamQuery {
	return NewUnitClient(_m.config).QueryExam(_m)
}

// QuerySection queries the "section" edge of the Unit entity.
func (_m *Unit) QuerySection() *SectionQuery {
	return NewUnitClient(_m.config).QuerySection(_m)
}

// QueryTopic queries the "topic" edge of the Unit entity.
func (_m *Unit) QueryTopic() *TopicQuery {
	return NewUnitClient(_m.config).QueryTopic(_m)
}

// QueryProblems queries the "problems" edge of the Unit entity.
func (_m *Unit) QueryProblems() *ProblemQuery {
	return NewUnitClient(_m.config).QueryProblems(_m)
}

// Update returns a builder for updating this Unit.
// Note that you need to call Unit.Unwrap() before calling this method if this Unit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Unit) Update() *UnitUpdateOne {
	return NewUnitClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Unit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Unit) Unwrap() *Unit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Unit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Unit) String() string {
	var builder strings.Builder
	builder.WriteString("Unit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("seq=")
	builder.WriteString(fmt.Sprintf("%v", _m.Seq))
	builder.WriteString(", ")
	builder.WriteString("exam_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExamID))
	builder.WriteString(", ")
	if v := _m.SectionID; v != nil {
		builder.WriteString("section_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TopicID; v != nil {
		builder.WriteString("topic_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Units is a parsable slice of Unit.
type Units []*Unit
