// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"examination/internal/ent/exam"
	"examination/internal/ent/problem"
	"examination/internal/ent/section"
	"examination/internal/ent/topic"
	"examination/internal/ent/unit"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UnitCreate is the builder for creating a Unit entity.
type UnitCreate struct {
	config
	mutation *UnitMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *UnitCreate) SetTitle(v string) *UnitCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSeq sets the "seq" field.
func (_c *UnitCreate) SetSeq(v int) *UnitCreate {
	_c.mutation.SetSeq(v)
	return _c
}

// SetExamID sets the "exam_id" field.
func (_c *UnitCreate) SetExamID(v int) *UnitCreate {
	_c.mutation.SetExamID(v)
	return _c
}

// SetSectionID sets the "section_id" field.
func (_c *UnitCreate) SetSectionID(v int) *UnitCreate {
	_c.mutation.SetSectionID(v)
	return _c
}

// SetNillableSectionID sets the "section_id" field if the given value is not nil.
func (_c *UnitCreate) SetNillableSectionID(v *int) *UnitCreate {
	if v != nil {
		_c.SetSectionID(*v)
	}
	return _c
}

// SetTopicID sets the "topic_id" field.
func (_c *UnitCreate) SetTopicID(v int) *UnitCreate {
	_c.mutation.SetTopicID(v)
	return _c
}

// SetNillableTopicID sets the "topic_id" field if the given value is not nil.
func (_c *UnitCreate) SetNillableTopicID(v *int) *UnitCreate {
	if v != nil {
		_c.SetTopicID(*v)
	}
	return _c
}

// SetExam sets the "exam" edge to the Exam entity.
func (_c *UnitCreate) SetExam(v *Exam) *UnitCreate {
	return _c.SetExamID(v.ID)
}

// SetSection sets the "section" edge to the Section entity.
func (_c *UnitCreate) SetSection(v *Section) *UnitCreate {
	return _c.SetSectionID(v.ID)
}

// SetTopic sets the "topic" edge to the Topic entity.
func (_c *UnitCreate) SetTopic(v *Topic) *UnitCreate {
	return _c.SetTopicID(v.ID)
}

// AddProblemIDs adds the "problems" edge to the Problem entity by IDs.
func (_c *UnitCreate) AddProblemIDs(ids ...int) *UnitCreate {
	_c.mutation.AddProblemIDs(ids...)
	return _c
}

// AddProblems adds the "problems" edges to the Problem entity.
func (_c *UnitCreate) AddProblems(v ...*Problem) *UnitCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProblemIDs(ids...)
}

// Mutation returns the UnitMutation object of the builder.
func (_c *UnitCreate) Mutation() *UnitMutation {
	return _c.mutation
}

// Save creates the Unit in the database.
func (_c *UnitCreate) Save(ctx context.Context) (*Unit, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UnitCreate) SaveX(ctx context.Context) *Unit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnitCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnitCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UnitCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Unit.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := unit.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Unit.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Seq(); !ok {
		return &ValidationError{Name: "seq", err: errors.New(`ent: missing required field "Unit.seq"`)}
	}
	if _, ok := _c.mutation.ExamID(); !ok {
		return &ValidationError{Name: "exam_id", err: errors.New(`ent: missing required field "Unit.exam_id"`)}
	}
	if len(_c.mutation.ExamIDs()) == 0 {
		return &ValidationError{Name: "exam", err: errors.New(`ent: missing required edge "Unit.exam"`)}
	}
	return nil
}

func (_c *UnitCreate) sqlSave(ctx context.Context) (*Unit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UnitCreate) createSpec() (*Unit, *sqlgraph.CreateSpec) {
	var (
		_node = &Unit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(unit.Table, sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(unit.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Seq(); ok {
		_spec.SetField(unit.FieldSeq, field.TypeInt, value)
		_node.Seq = value
	}
	if nodes := _c.mutation.ExamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.ExamTable,
			Columns: []string{unit.ExamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ExamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.SectionTable,
			Columns: []string{unit.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SectionID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TopicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.TopicTable,
			Columns: []string{unit.TopicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TopicID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProblemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unit.ProblemsTable,
			Columns: []string{unit.ProblemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UnitCreateBulk is the builder for creating many Unit entities in bulk.
type UnitCreateBulk struct {
	config
	err      error
	builders []*UnitCreate
}

// Save creates the Unit entities in the database.
func (_c *UnitCreateBulk) Save(ctx context.Context) ([]*Unit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Unit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UnitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UnitCreateBulk) SaveX(ctx context.Context) []*Unit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnitCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnitCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
