// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"examination/internal/ent/exam"
	"examination/internal/ent/predicate"
	"examination/internal/ent/problem"
	"examination/internal/ent/section"
	"examination/internal/ent/topic"
	"examination/internal/ent/unit"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UnitUpdate is the builder for updating Unit entities.
type UnitUpdate struct {
	config
	hooks    []Hook
	mutation *UnitMutation
}

// Where appends a list predicates to the UnitUpdate builder.
func (_u *UnitUpdate) Where(ps ...predicate.Unit) *UnitUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *UnitUpdate) SetTitle(v string) *UnitUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *UnitUpdate) SetNillableTitle(v *string) *UnitUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSeq sets the "seq" field.
func (_u *UnitUpdate) SetSeq(v int) *UnitUpdate {
	_u.mutation.ResetSeq()
	_u.mutation.SetSeq(v)
	return _u
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_u *UnitUpdate) SetNillableSeq(v *int) *UnitUpdate {
	if v != nil {
		_u.SetSeq(*v)
	}
	return _u
}

// AddSeq adds value to the "seq" field.
func (_u *UnitUpdate) AddSeq(v int) *UnitUpdate {
	_u.mutation.AddSeq(v)
	return _u
}

// SetExamID sets the "exam_id" field.
func (_u *UnitUpdate) SetExamID(v int) *UnitUpdate {
	_u.mutation.SetExamID(v)
	return _u
}

// SetNillableExamID sets the "exam_id" field if the given value is not nil.
func (_u *UnitUpdate) SetNillableExamID(v *int) *UnitUpdate {
	if v != nil {
		_u.SetExamID(*v)
	}
	return _u
}

// SetSectionID sets the "section_id" field.
func (_u *UnitUpdate) SetSectionID(v int) *UnitUpdate {
	_u.mutation.SetSectionID(v)
	return _u
}

// SetNillableSectionID sets the "section_id" field if the given value is not nil.
func (_u *UnitUpdate) SetNillableSectionID(v *int) *UnitUpdate {
	if v != nil {
		_u.SetSectionID(*v)
	}
	return _u
}

// ClearSectionID clears the value of the "section_id" field.
func (_u *UnitUpdate) ClearSectionID() *UnitUpdate {
	_u.mutation.ClearSectionID()
	return _u
}

// SetTopicID sets the "topic_id" field.
func (_u *UnitUpdate) SetTopicID(v int) *UnitUpdate {
	_u.mutation.SetTopicID(v)
	return _u
}

// SetNillableTopicID sets the "topic_id" field if the given value is not nil.
func (_u *UnitUpdate) SetNillableTopicID(v *int) *UnitUpdate {
	if v != nil {
		_u.SetTopicID(*v)
	}
	return _u
}

// ClearTopicID clears the value of the "topic_id" field.
func (_u *UnitUpdate) ClearTopicID() *UnitUpdate {
	_u.mutation.ClearTopicID()
	return _u
}

// SetExam sets the "exam" edge to the Exam entity.
func (_u *UnitUpdate) SetExam(v *Exam) *UnitUpdate {
	return _u.SetExamID(v.ID)
}

// SetSection sets the "section" edge to the Section entity.
func (_u *UnitUpdate) SetSection(v *Section) *UnitUpdate {
	return _u.SetSectionID(v.ID)
}

// SetTopic sets the "topic" edge to the Topic entity.
func (_u *UnitUpdate) SetTopic(v *Topic) *UnitUpdate {
	return _u.SetTopicID(v.ID)
}

// AddProblemIDs adds the "problems" edge to the Problem entity by IDs.
func (_u *UnitUpdate) AddProblemIDs(ids ...int) *UnitUpdate {
	_u.mutation.AddProblemIDs(ids...)
	return _u
}

// AddProblems adds the "problems" edges to the Problem entity.
func (_u *UnitUpdate) AddProblems(v ...*Problem) *UnitUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProblemIDs(ids...)
}

// Mutation returns the UnitMutation object of the builder.
func (_u *UnitUpdate) Mutation() *UnitMutation {
	return _u.mutation
}

// ClearExam clears the "exam" edge to the Exam entity.
func (_u *UnitUpdate) ClearExam() *UnitUpdate {
	_u.mutation.ClearExam()
	return _u
}

// ClearSection clears the "section" edge to the Section entity.
func (_u *UnitUpdate) ClearSection() *UnitUpdate {
	_u.mutation.ClearSection()
	return _u
}

// ClearTopic clears the "topic" edge to the Topic entity.
func (_u *UnitUpdate) ClearTopic() *UnitUpdate {
	_u.mutation.ClearTopic()
	return _u
}

// ClearProblems clears all "problems" edges to the Problem entity.
func (_u *UnitUpdate) ClearProblems() *UnitUpdate {
	_u.mutation.ClearProblems()
	return _u
}

// RemoveProblemIDs removes the "problems" edge to Problem entities by IDs.
func (_u *UnitUpdate) RemoveProblemIDs(ids ...int) *UnitUpdate {
	_u.mutation.RemoveProblemIDs(ids...)
	return _u
}

// RemoveProblems removes "problems" edges to Problem entities.
func (_u *UnitUpdate) RemoveProblems(v ...*Problem) *UnitUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProblemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UnitUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UnitUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UnitUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UnitUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UnitUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := unit.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Unit.title": %w`, err)}
		}
	}
	if _u.mutation.ExamCleared() && len(_u.mutation.ExamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Unit.exam"`)
	}
	return nil
}

func (_u *UnitUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(unit.Table, unit.Columns, sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(unit.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Seq(); ok {
		_spec.SetField(unit.FieldSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeq(); ok {
		_spec.AddField(unit.FieldSeq, field.TypeInt, value)
	}
	if _u.mutation.ExamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.ExamTable,
			Columns: []string{unit.ExamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.ExamTable,
			Columns: []string{unit.ExamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.SectionTable,
			Columns: []string{unit.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.SectionTable,
			Columns: []string{unit.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TopicCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.TopicTable,
			Columns: []string{unit.TopicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TopicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.TopicTable,
			Columns: []string{unit.TopicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProblemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unit.ProblemsTable,
			Columns: []string{unit.ProblemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProblemsIDs(); len(nodes) > 0 && !_u.mutation.ProblemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unit.ProblemsTable,
			Columns: []string{unit.ProblemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unit.ProblemsTable,
			Columns: []string{unit.ProblemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{unit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UnitUpdateOne is the builder for updating a single Unit entity.
type UnitUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UnitMutation
}

// SetTitle sets the "title" field.
func (_u *UnitUpdateOne) SetTitle(v string) *UnitUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *UnitUpdateOne) SetNillableTitle(v *string) *UnitUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSeq sets the "seq" field.
func (_u *UnitUpdateOne) SetSeq(v int) *UnitUpdateOne {
	_u.mutation.ResetSeq()
	_u.mutation.SetSeq(v)
	return _u
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_u *UnitUpdateOne) SetNillableSeq(v *int) *UnitUpdateOne {
	if v != nil {
		_u.SetSeq(*v)
	}
	return _u
}

// AddSeq adds value to the "seq" field.
func (_u *UnitUpdateOne) AddSeq(v int) *UnitUpdateOne {
	_u.mutation.AddSeq(v)
	return _u
}

// SetExamID sets the "exam_id" field.
func (_u *UnitUpdateOne) SetExamID(v int) *UnitUpdateOne {
	_u.mutation.SetExamID(v)
	return _u
}

// SetNillableExamID sets the "exam_id" field if the given value is not nil.
func (_u *UnitUpdateOne) SetNillableExamID(v *int) *UnitUpdateOne {
	if v != nil {
		_u.SetExamID(*v)
	}
	return _u
}

// SetSectionID sets the "section_id" field.
func (_u *UnitUpdateOne) SetSectionID(v int) *UnitUpdateOne {
	_u.mutation.SetSectionID(v)
	return _u
}

// SetNillableSectionID sets the "section_id" field if the given value is not nil.
func (_u *UnitUpdateOne) SetNillableSectionID(v *int) *UnitUpdateOne {
	if v != nil {
		_u.SetSectionID(*v)
	}
	return _u
}

// ClearSectionID clears the value of the "section_id" field.
func (_u *UnitUpdateOne) ClearSectionID() *UnitUpdateOne {
	_u.mutation.ClearSectionID()
	return _u
}

// SetTopicID sets the "topic_id" field.
func (_u *UnitUpdateOne) SetTopicID(v int) *UnitUpdateOne {
	_u.mutation.SetTopicID(v)
	return _u
}

// SetNillableTopicID sets the "topic_id" field if the given value is not nil.
func (_u *UnitUpdateOne) SetNillableTopicID(v *int) *UnitUpdateOne {
	if v != nil {
		_u.SetTopicID(*v)
	}
	return _u
}

// ClearTopicID clears the value of the "topic_id" field.
func (_u *UnitUpdateOne) ClearTopicID() *UnitUpdateOne {
	_u.mutation.ClearTopicID()
	return _u
}

// SetExam sets the "exam" edge to the Exam entity.
func (_u *UnitUpdateOne) SetExam(v *Exam) *UnitUpdateOne {
	return _u.SetExamID(v.ID)
}

// SetSection sets the "section" edge to the Section entity.
func (_u *UnitUpdateOne) SetSection(v *Section) *UnitUpdateOne {
	return _u.SetSectionID(v.ID)
}

// SetTopic sets the "topic" edge to the Topic entity.
func (_u *UnitUpdateOne) SetTopic(v *Topic) *UnitUpdateOne {
	return _u.SetTopicID(v.ID)
}

// AddProblemIDs adds the "problems" edge to the Problem entity by IDs.
func (_u *UnitUpdateOne) AddProblemIDs(ids ...int) *UnitUpdateOne {
	_u.mutation.AddProblemIDs(ids...)
	return _u
}

// AddProblems adds the "problems" edges to the Problem entity.
func (_u *UnitUpdateOne) AddProblems(v ...*Problem) *UnitUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProblemIDs(ids...)
}

// Mutation returns the UnitMutation object of the builder.
func (_u *UnitUpdateOne) Mutation() *UnitMutation {
	return _u.mutation
}

// ClearExam clears the "exam" edge to the Exam entity.
func (_u *UnitUpdateOne) ClearExam() *UnitUpdateOne {
	_u.mutation.ClearExam()
	return _u
}

// ClearSection clears the "section" edge to the Section entity.
func (_u *UnitUpdateOne) ClearSection() *UnitUpdateOne {
	_u.mutation.ClearSection()
	return _u
}

// ClearTopic clears the "topic" edge to the Topic entity.
func (_u *UnitUpdateOne) ClearTopic() *UnitUpdateOne {
	_u.mutation.ClearTopic()
	return _u
}

// ClearProblems clears all "problems" edges to the Problem entity.
func (_u *UnitUpdateOne) ClearProblems() *UnitUpdateOne {
	_u.mutation.ClearProblems()
	return _u
}

// RemoveProblemIDs removes the "problems" edge to Problem entities by IDs.
func (_u *UnitUpdateOne) RemoveProblemIDs(ids ...int) *UnitUpdateOne {
	_u.mutation.RemoveProblemIDs(ids...)
	return _u
}

// RemoveProblems removes "problems" edges to Problem entities.
func (_u *UnitUpdateOne) RemoveProblems(v ...*Problem) *UnitUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProblemIDs(ids...)
}

// Where appends a list predicates to the UnitUpdate builder.
func (_u *UnitUpdateOne) Where(ps ...predicate.Unit) *UnitUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UnitUpdateOne) Select(field string, fields ...string) *UnitUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Unit entity.
func (_u *UnitUpdateOne) Save(ctx context.Context) (*Unit, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UnitUpdateOne) SaveX(ctx context.Context) *Unit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UnitUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UnitUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UnitUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := unit.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Unit.title": %w`, err)}
		}
	}
	if _u.mutation.ExamCleared() && len(_u.mutation.ExamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Unit.exam"`)
	}
	return nil
}

func (_u *UnitUpdateOne) sqlSave(ctx context.Context) (_node *Unit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(unit.Table, unit.Columns, sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Unit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, unit.FieldID)
		for _, f := range fields {
			if !unit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != unit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(unit.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Seq(); ok {
		_spec.SetField(unit.FieldSeq, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeq(); ok {
		_spec.AddField(unit.FieldSeq, field.TypeInt, value)
	}
	if _u.mutation.ExamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.ExamTable,
			Columns: []string{unit.ExamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.ExamTable,
			Columns: []string{unit.ExamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.SectionTable,
			Columns: []string{unit.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.SectionTable,
			Columns: []string{unit.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TopicCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.TopicTable,
			Columns: []string{unit.TopicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TopicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.TopicTable,
			Columns: []string{unit.TopicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProblemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unit.ProblemsTable,
			Columns: []string{unit.ProblemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProblemsIDs(); len(nodes) > 0 && !_u.mutation.ProblemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unit.ProblemsTable,
			Columns: []string{unit.ProblemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unit.ProblemsTable,
			Columns: []string{unit.ProblemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Unit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{unit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
