// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"examination/internal/ent/exam"
	"examination/internal/ent/predicate"
	"examination/internal/ent/problem"
	"examination/internal/ent/versionrule"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VersionRuleQuery is the builder for querying VersionRule entities.
type VersionRuleQuery struct {
	config
	ctx         *QueryContext
	order       []versionrule.OrderOption
	inters      []Interceptor
	predicates  []predicate.VersionRule
	withExam    *ExamQuery
	withProblem *ProblemQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VersionRuleQuery builder.
func (_q *VersionRuleQuery) Where(ps ...predicate.VersionRule) *VersionRuleQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *VersionRuleQuery) Limit(limit int) *VersionRuleQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *VersionRuleQuery) Offset(offset int) *VersionRuleQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *VersionRuleQuery) Unique(unique bool) *VersionRuleQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *VersionRuleQuery) Order(o ...versionrule.OrderOption) *VersionRuleQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryExam chains the current query on the "exam" edge.
func (_q *VersionRuleQuery) QueryExam() *ExamQuery {
	query := (&ExamClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(versionrule.Table, versionrule.FieldID, selector),
			sqlgraph.To(exam.Table, exam.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, versionrule.ExamTable, versionrule.ExamColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProblem chains the current query on the "problem" edge.
func (_q *VersionRuleQuery) QueryProblem() *ProblemQuery {
	query := (&ProblemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(versionrule.Table, versionrule.FieldID, selector),
			sqlgraph.To(problem.Table, problem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, versionrule.ProblemTable, versionrule.ProblemColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VersionRule entity from the query.
// Returns a *NotFoundError when no VersionRule was found.
func (_q *VersionRuleQuery) First(ctx context.Context) (*VersionRule, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{versionrule.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *VersionRuleQuery) FirstX(ctx context.Context) *VersionRule {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VersionRule ID from the query.
// Returns a *NotFoundError when no VersionRule ID was found.
func (_q *VersionRuleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{versionrule.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *VersionRuleQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VersionRule entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VersionRule entity is found.
// Returns a *NotFoundError when no VersionRule entities are found.
func (_q *VersionRuleQuery) Only(ctx context.Context) (*VersionRule, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{versionrule.Label}
	default:
		return nil, &NotSingularError{versionrule.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *VersionRuleQuery) OnlyX(ctx context.Context) *VersionRule {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VersionRule ID in the query.
// Returns a *NotSingularError when more than one VersionRule ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *VersionRuleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{versionrule.Label}
	default:
		err = &NotSingularError{versionrule.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *VersionRuleQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VersionRules.
func (_q *VersionRuleQuery) All(ctx context.Context) ([]*VersionRule, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VersionRule, *VersionRuleQuery]()
	return withInterceptors[[]*VersionRule](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *VersionRuleQuery) AllX(ctx context.Context) []*VersionRule {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VersionRule IDs.
func (_q *VersionRuleQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(versionrule.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *VersionRuleQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *VersionRuleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*VersionRuleQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *VersionRuleQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *VersionRuleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *VersionRuleQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VersionRuleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *VersionRuleQuery) Clone() *VersionRuleQuery {
	if _q == nil {
		return nil
	}
	return &VersionRuleQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]versionrule.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.VersionRule{}, _q.predicates...),
		withExam:    _q.withExam.Clone(),
		withProblem: _q.withProblem.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithExam tells the query-builder to eager-load the nodes that are connected to
// the "exam" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VersionRuleQuery) WithExam(opts ...func(*ExamQuery)) *VersionRuleQuery {
	query := (&ExamClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withExam = query
	return _q
}

// WithProblem tells the query-builder to eager-load the nodes that are connected to
// the "problem" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VersionRuleQuery) WithProblem(opts ...func(*ProblemQuery)) *VersionRuleQuery {
	query := (&ProblemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProblem = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Year int `json:"year,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VersionRule.Query().
//		GroupBy(versionrule.FieldYear).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *VersionRuleQuery) GroupBy(field string, fields ...string) *VersionRuleGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VersionRuleGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = versionrule.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Year int `json:"year,omitempty"`
//	}
//
//	client.VersionRule.Query().
//		Select(versionrule.FieldYear).
//		Scan(ctx, &v)
func (_q *VersionRuleQuery) Select(fields ...string) *VersionRuleSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &VersionRuleSelect{VersionRuleQuery: _q}
	sbuild.label = versionrule.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VersionRuleSelect configured with the given aggregations.
func (_q *VersionRuleQuery) Aggregate(fns ...AggregateFunc) *VersionRuleSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *VersionRuleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !versionrule.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *VersionRuleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VersionRule, error) {
	var (
		nodes       = []*VersionRule{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withExam != nil,
			_q.withProblem != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VersionRule).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VersionRule{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withExam; query != nil {
		if err := _q.loadExam(ctx, query, nodes, nil,
			func(n *VersionRule, e *Exam) { n.Edges.Exam = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProblem; query != nil {
		if err := _q.loadProblem(ctx, query, nodes, nil,
			func(n *VersionRule, e *Problem) { n.Edges.Problem = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *VersionRuleQuery) loadExam(ctx context.Context, query *ExamQuery, nodes []*VersionRule, init func(*VersionRule), assign func(*VersionRule, *Exam)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*VersionRule)
	for i := range nodes {
		fk := nodes[i].ExamID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(exam.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "exam_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *VersionRuleQuery) loadProblem(ctx context.Context, query *ProblemQuery, nodes []*VersionRule, init func(*VersionRule), assign func(*VersionRule, *Problem)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*VersionRule)
	for i := range nodes {
		if nodes[i].ProblemID == nil {
			continue
		}
		fk := *nodes[i].ProblemID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(problem.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "problem_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *VersionRuleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *VersionRuleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(versionrule.Table, versionrule.Columns, sqlgraph.NewFieldSpec(versionrule.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, versionrule.FieldID)
		for i := range fields {
			if fields[i] != versionrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withExam != nil {
			_spec.Node.AddColumnOnce(versionrule.FieldExamID)
		}
		if _q.withProblem != nil {
			_spec.Node.AddColumnOnce(versionrule.FieldProblemID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *VersionRuleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(versionrule.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = versionrule.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VersionRuleGroupBy is the group-by builder for VersionRule entities.
type VersionRuleGroupBy struct {
	selector
	build *VersionRuleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *VersionRuleGroupBy) Aggregate(fns ...AggregateFunc) *VersionRuleGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *VersionRuleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VersionRuleQuery, *VersionRuleGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *VersionRuleGroupBy) sqlScan(ctx context.Context, root *VersionRuleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VersionRuleSelect is the builder for selecting fields of VersionRule entities.
type VersionRuleSelect struct {
	*VersionRuleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *VersionRuleSelect) Aggregate(fns ...AggregateFunc) *VersionRuleSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *VersionRuleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VersionRuleQuery, *VersionRuleSelect](ctx, _s.VersionRuleQuery, _s, _s.inters, v)
}

func (_s *VersionRuleSelect) sqlScan(ctx context.Context, root *VersionRuleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
