// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"examination/internal/ent/exam"
	"examination/internal/ent/predicate"
	"examination/internal/ent/problem"
	"examination/internal/ent/versionrule"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VersionRuleUpdate is the builder for updating VersionRule entities.
type VersionRuleUpdate struct {
	config
	hooks    []Hook
	mutation *VersionRuleMutation
}

// Where appends a list predicates to the VersionRuleUpdate builder.
func (_u *VersionRuleUpdate) Where(ps ...predicate.VersionRule) *VersionRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetYear sets the "year" field.
func (_u *VersionRuleUpdate) SetYear(v int) *VersionRuleUpdate {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *VersionRuleUpdate) SetNillableYear(v *int) *VersionRuleUpdate {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *VersionRuleUpdate) AddYear(v int) *VersionRuleUpdate {
	_u.mutation.AddYear(v)
	return _u
}

// ClearYear clears the value of the "year" field.
func (_u *VersionRuleUpdate) ClearYear() *VersionRuleUpdate {
	_u.mutation.ClearYear()
	return _u
}

// SetRound sets the "round" field.
func (_u *VersionRuleUpdate) SetRound(v int) *VersionRuleUpdate {
	_u.mutation.ResetRound()
	_u.mutation.SetRound(v)
	return _u
}

// SetNillableRound sets the "round" field if the given value is not nil.
func (_u *VersionRuleUpdate) SetNillableRound(v *int) *VersionRuleUpdate {
	if v != nil {
		_u.SetRound(*v)
	}
	return _u
}

// AddRound adds value to the "round" field.
func (_u *VersionRuleUpdate) AddRound(v int) *VersionRuleUpdate {
	_u.mutation.AddRound(v)
	return _u
}

// ClearRound clears the value of the "round" field.
func (_u *VersionRuleUpdate) ClearRound() *VersionRuleUpdate {
	_u.mutation.ClearRound()
	return _u
}

// SetCategory sets the "category" field.
func (_u *VersionRuleUpdate) SetCategory(v string) *VersionRuleUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *VersionRuleUpdate) SetNillableCategory(v *string) *VersionRuleUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *VersionRuleUpdate) ClearCategory() *VersionRuleUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetOperator sets the "operator" field.
func (_u *VersionRuleUpdate) SetOperator(v versionrule.Operator) *VersionRuleUpdate {
	_u.mutation.SetOperator(v)
	return _u
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_u *VersionRuleUpdate) SetNillableOperator(v *versionrule.Operator) *VersionRuleUpdate {
	if v != nil {
		_u.SetOperator(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *VersionRuleUpdate) SetStatus(v versionrule.Status) *VersionRuleUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VersionRuleUpdate) SetNillableStatus(v *versionrule.Status) *VersionRuleUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExamID sets the "exam_id" field.
func (_u *VersionRuleUpdate) SetExamID(v int) *VersionRuleUpdate {
	_u.mutation.SetExamID(v)
	return _u
}

// SetNillableExamID sets the "exam_id" field if the given value is not nil.
func (_u *VersionRuleUpdate) SetNillableExamID(v *int) *VersionRuleUpdate {
	if v != nil {
		_u.SetExamID(*v)
	}
	return _u
}

// SetProblemID sets the "problem_id" field.
func (_u *VersionRuleUpdate) SetProblemID(v int) *VersionRuleUpdate {
	_u.mutation.SetProblemID(v)
	return _u
}

// SetNillableProblemID sets the "problem_id" field if the given value is not nil.
func (_u *VersionRuleUpdate) SetNillableProblemID(v *int) *VersionRuleUpdate {
	if v != nil {
		_u.SetProblemID(*v)
	}
	return _u
}

// ClearProblemID clears the value of the "problem_id" field.
func (_u *VersionRuleUpdate) ClearProblemID() *VersionRuleUpdate {
	_u.mutation.ClearProblemID()
	return _u
}

// SetExam sets the "exam" edge to the Exam entity.
func (_u *VersionRuleUpdate) SetExam(v *Exam) *VersionRuleUpdate {
	return _u.SetExamID(v.ID)
}

// SetProblem sets the "problem" edge to the Problem entity.
func (_u *VersionRuleUpdate) SetProblem(v *Problem) *VersionRuleUpdate {
	return _u.SetProblemID(v.ID)
}

// Mutation returns the VersionRuleMutation object of the builder.
func (_u *VersionRuleUpdate) Mutation() *VersionRuleMutation {
	return _u.mutation
}

// ClearExam clears the "exam" edge to the Exam entity.
func (_u *VersionRuleUpdate) ClearExam() *VersionRuleUpdate {
	_u.mutation.ClearExam()
	return _u
}

// ClearProblem clears the "problem" edge to the Problem entity.
func (_u *VersionRuleUpdate) ClearProblem() *VersionRuleUpdate {
	_u.mutation.ClearProblem()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VersionRuleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VersionRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VersionRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VersionRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VersionRuleUpdate) check() error {
	if v, ok := _u.mutation.Operator(); ok {
		if err := versionrule.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "VersionRule.operator": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := versionrule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VersionRule.status": %w`, err)}
		}
	}
	if _u.mutation.ExamCleared() && len(_u.mutation.ExamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VersionRule.exam"`)
	}
	return nil
}

func (_u *VersionRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(versionrule.Table, versionrule.Columns, sqlgraph.NewFieldSpec(versionrule.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(versionrule.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(versionrule.FieldYear, field.TypeInt, value)
	}
	if _u.mutation.YearCleared() {
		_spec.ClearField(versionrule.FieldYear, field.TypeInt)
	}
	if value, ok := _u.mutation.Round(); ok {
		_spec.SetField(versionrule.FieldRound, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRound(); ok {
		_spec.AddField(versionrule.FieldRound, field.TypeInt, value)
	}
	if _u.mutation.RoundCleared() {
		_spec.ClearField(versionrule.FieldRound, field.TypeInt)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(versionrule.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(versionrule.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Operator(); ok {
		_spec.SetField(versionrule.FieldOperator, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(versionrule.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.ExamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   versionrule.ExamTable,
			Columns: []string{versionrule.ExamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   versionrule.ExamTable,
			Columns: []string{versionrule.ExamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProblemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   versionrule.ProblemTable,
			Columns: []string{versionrule.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   versionrule.ProblemTable,
			Columns: []string{versionrule.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{versionrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VersionRuleUpdateOne is the builder for updating a single VersionRule entity.
type VersionRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VersionRuleMutation
}

// SetYear sets the "year" field.
func (_u *VersionRuleUpdateOne) SetYear(v int) *VersionRuleUpdateOne {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *VersionRuleUpdateOne) SetNillableYear(v *int) *VersionRuleUpdateOne {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *VersionRuleUpdateOne) AddYear(v int) *VersionRuleUpdateOne {
	_u.mutation.AddYear(v)
	return _u
}

// ClearYear clears the value of the "year" field.
func (_u *VersionRuleUpdateOne) ClearYear() *VersionRuleUpdateOne {
	_u.mutation.ClearYear()
	return _u
}

// SetRound sets the "round" field.
func (_u *VersionRuleUpdateOne) SetRound(v int) *VersionRuleUpdateOne {
	_u.mutation.ResetRound()
	_u.mutation.SetRound(v)
	return _u
}

// SetNillableRound sets the "round" field if the given value is not nil.
func (_u *VersionRuleUpdateOne) SetNillableRound(v *int) *VersionRuleUpdateOne {
	if v != nil {
		_u.SetRound(*v)
	}
	return _u
}

// AddRound adds value to the "round" field.
func (_u *VersionRuleUpdateOne) AddRound(v int) *VersionRuleUpdateOne {
	_u.mutation.AddRound(v)
	return _u
}

// ClearRound clears the value of the "round" field.
func (_u *VersionRuleUpdateOne) ClearRound() *VersionRuleUpdateOne {
	_u.mutation.ClearRound()
	return _u
}

// SetCategory sets the "category" field.
func (_u *VersionRuleUpdateOne) SetCategory(v string) *VersionRuleUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *VersionRuleUpdateOne) SetNillableCategory(v *string) *VersionRuleUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *VersionRuleUpdateOne) ClearCategory() *VersionRuleUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetOperator sets the "operator" field.
func (_u *VersionRuleUpdateOne) SetOperator(v versionrule.Operator) *VersionRuleUpdateOne {
	_u.mutation.SetOperator(v)
	return _u
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_u *VersionRuleUpdateOne) SetNillableOperator(v *versionrule.Operator) *VersionRuleUpdateOne {
	if v != nil {
		_u.SetOperator(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *VersionRuleUpdateOne) SetStatus(v versionrule.Status) *VersionRuleUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VersionRuleUpdateOne) SetNillableStatus(v *versionrule.Status) *VersionRuleUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExamID sets the "exam_id" field.
func (_u *VersionRuleUpdateOne) SetExamID(v int) *VersionRuleUpdateOne {
	_u.mutation.SetExamID(v)
	return _u
}

// SetNillableExamID sets the "exam_id" field if the given value is not nil.
func (_u *VersionRuleUpdateOne) SetNillableExamID(v *int) *VersionRuleUpdateOne {
	if v != nil {
		_u.SetExamID(*v)
	}
	return _u
}

// SetProblemID sets the "problem_id" field.
func (_u *VersionRuleUpdateOne) SetProblemID(v int) *VersionRuleUpdateOne {
	_u.mutation.SetProblemID(v)
	return _u
}

// SetNillableProblemID sets the "problem_id" field if the given value is not nil.
func (_u *VersionRuleUpdateOne) SetNillableProblemID(v *int) *VersionRuleUpdateOne {
	if v != nil {
		_u.SetProblemID(*v)
	}
	return _u
}

// ClearProblemID clears the value of the "problem_id" field.
func (_u *VersionRuleUpdateOne) ClearProblemID() *VersionRuleUpdateOne {
	_u.mutation.ClearProblemID()
	return _u
}

// SetExam sets the "exam" edge to the Exam entity.
func (_u *VersionRuleUpdateOne) SetExam(v *Exam) *VersionRuleUpdateOne {
	return _u.SetExamID(v.ID)
}

// SetProblem sets the "problem" edge to the Problem entity.
func (_u *VersionRuleUpdateOne) SetProblem(v *Problem) *VersionRuleUpdateOne {
	return _u.SetProblemID(v.ID)
}

// Mutation returns the VersionRuleMutation object of the builder.
func (_u *VersionRuleUpdateOne) Mutation() *VersionRuleMutation {
	return _u.mutation
}

// ClearExam clears the "exam" edge to the Exam entity.
func (_u *VersionRuleUpdateOne) ClearExam() *VersionRuleUpdateOne {
	_u.mutation.ClearExam()
	return _u
}

// ClearProblem clears the "problem" edge to the Problem entity.
func (_u *VersionRuleUpdateOne) ClearProblem() *VersionRuleUpdateOne {
	_u.mutation.ClearProblem()
	return _u
}

// Where appends a list predicates to the VersionRuleUpdate builder.
func (_u *VersionRuleUpdateOne) Where(ps ...predicate.VersionRule) *VersionRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VersionRuleUpdateOne) Select(field string, fields ...string) *VersionRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VersionRule entity.
func (_u *VersionRuleUpdateOne) Save(ctx context.Context) (*VersionRule, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VersionRuleUpdateOne) SaveX(ctx context.Context) *VersionRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VersionRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VersionRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VersionRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Operator(); ok {
		if err := versionrule.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "VersionRule.operator": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := versionrule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VersionRule.status": %w`, err)}
		}
	}
	if _u.mutation.ExamCleared() && len(_u.mutation.ExamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VersionRule.exam"`)
	}
	return nil
}

func (_u *VersionRuleUpdateOne) sqlSave(ctx context.Context) (_node *VersionRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(versionrule.Table, versionrule.Columns, sqlgraph.NewFieldSpec(versionrule.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VersionRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, versionrule.FieldID)
		for _, f := range fields {
			if !versionrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != versionrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(versionrule.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(versionrule.FieldYear, field.TypeInt, value)
	}
	if _u.mutation.YearCleared() {
		_spec.ClearField(versionrule.FieldYear, field.TypeInt)
	}
	if value, ok := _u.mutation.Round(); ok {
		_spec.SetField(versionrule.FieldRound, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRound(); ok {
		_spec.AddField(versionrule.FieldRound, field.TypeInt, value)
	}
	if _u.mutation.RoundCleared() {
		_spec.ClearField(versionrule.FieldRound, field.TypeInt)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(versionrule.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(versionrule.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Operator(); ok {
		_spec.SetField(versionrule.FieldOperator, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(versionrule.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.ExamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   versionrule.ExamTable,
			Columns: []string{versionrule.ExamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   versionrule.ExamTable,
			Columns: []string{versionrule.ExamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProblemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   versionrule.ProblemTable,
			Columns: []string{versionrule.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   versionrule.ProblemTable,
			Columns: []string{versionrule.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VersionRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{versionrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
