// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Choice is the predicate function for choice builders.
type Choice func(*sql.Selector)

// Exam is the predicate function for exam builders.
type Exam func(*sql.Selector)

// Problem is the predicate function for problem builders.
type Problem func(*sql.Selector)

// ProblemTranslation is the predicate function for problemtranslation builders.
type ProblemTranslation func(*sql.Selector)

// Section is the predicate function for section builders.
type Section func(*sql.Selector)

// Topic is the predicate function for topic builders.
type Topic func(*sql.Selector)

// Unit is the predicate function for unit builders.
type Unit func(*sql.Selector)

// VersionRule is the predicate function for versionrule builders.
type VersionRule func(*sql.Selector)
