// Code generated by ent, DO NOT EDIT.

package topic

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the topic type in the database.
	Label = "topic"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldSeq holds the string denoting the seq field in the database.
	FieldSeq = "seq"
	// FieldExamID holds the string denoting the exam_id field in the database.
	FieldExamID = "exam_id"
	// FieldSectionID holds the string denoting the section_id field in the database.
	FieldSectionID = "section_id"
	// EdgeExam holds the string denoting the exam edge name in mutations.
	EdgeExam = "exam"
	// EdgeSection holds the string denoting the section edge name in mutations.
	EdgeSection = "section"
	// EdgeUnits holds the string denoting the units edge name in mutations.
	EdgeUnits = "units"
	// Table holds the table name of the topic in the database.
	Table = "topics"
	// ExamTable is the table that holds the exam relation/edge.
	ExamTable = "topics"
	// ExamInverseTable is the table name for the Exam entity.
	// It exists in this package in order to avoid circular dependency with the "exam" package.
	ExamInverseTable = "exams"
	// ExamColumn is the table column denoting the exam relation/edge.
	ExamColumn = "exam_id"
	// SectionTable is the table that holds the section relation/edge.
	SectionTable = "topics"
	// SectionInverseTable is the table name for the Section entity.
	// It exists in this package in order to avoid circular dependency with the "section" package.
	SectionInverseTable = "sections"
	// SectionColumn is the table column denoting the section relation/edge.
	SectionColumn = "section_id"
	// UnitsTable is the table that holds the units relation/edge.
	UnitsTable = "units"
	// UnitsInverseTable is the table name for the Unit entity.
	// It exists in this package in order to avoid circular dependency with the "unit" package.
	UnitsInverseTable = "units"
	// UnitsColumn is the table column denoting the units relation/edge.
	UnitsColumn = "topic_id"
)

// Columns holds all SQL columns for topic fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldSeq,
	FieldExamID,
	FieldSectionID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
)

// OrderOption defines the ordering options for the Topic queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// BySeq orders the results by the seq field.
func BySeq(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeq, opts...).ToFunc()
}

// ByExamID orders the results by the exam_id field.
func ByExamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExamID, opts...).ToFunc()
}

// BySectionID orders the results by the section_id field.
func BySectionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSectionID, opts...).ToFunc()
}

// ByExamField orders the results by exam field.
func ByExamField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExamStep(), sql.OrderByField(field, opts...))
	}
}

// BySectionField orders the results by section field.
func BySectionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSectionStep(), sql.OrderByField(field, opts...))
	}
}

// ByUnitsCount orders the results by units count.
func ByUnitsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUnitsStep(), opts...)
	}
}

// ByUnits orders the results by units terms.
func ByUnits(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUnitsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newExamStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExamInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ExamTable, ExamColumn),
	)
}
func newSectionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SectionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SectionTable, SectionColumn),
	)
}
func newUnitsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UnitsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UnitsTable, UnitsColumn),
	)
}
