// Code generated by ent, DO NOT EDIT.

package exam

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the exam type in the database.
	Label = "exam"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldTimeLimit holds the string denoting the time_limit field in the database.
	FieldTimeLimit = "time_limit"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// EdgeSections holds the string denoting the sections edge name in mutations.
	EdgeSections = "sections"
	// EdgeTopics holds the string denoting the topics edge name in mutations.
	EdgeTopics = "topics"
	// EdgeUnits holds the string denoting the units edge name in mutations.
	EdgeUnits = "units"
	// EdgeVersionRules holds the string denoting the version_rules edge name in mutations.
	EdgeVersionRules = "version_rules"
	// Table holds the table name of the exam in the database.
	Table = "exams"
	// SectionsTable is the table that holds the sections relation/edge.
	SectionsTable = "sections"
	// SectionsInverseTable is the table name for the Section entity.
	// It exists in this package in order to avoid circular dependency with the "section" package.
	SectionsInverseTable = "sections"
	// SectionsColumn is the table column denoting the sections relation/edge.
	SectionsColumn = "exam_id"
	// TopicsTable is the table that holds the topics relation/edge.
	TopicsTable = "topics"
	// TopicsInverseTable is the table name for the Topic entity.
	// It exists in this package in order to avoid circular dependency with the "topic" package.
	TopicsInverseTable = "topics"
	// TopicsColumn is the table column denoting the topics relation/edge.
	TopicsColumn = "exam_id"
	// UnitsTable is the table that holds the units relation/edge.
	UnitsTable = "units"
	// UnitsInverseTable is the table name for the Unit entity.
	// It exists in this package in order to avoid circular dependency with the "unit" package.
	UnitsInverseTable = "units"
	// UnitsColumn is the table column denoting the units relation/edge.
	UnitsColumn = "exam_id"
	// VersionRulesTable is the table that holds the version_rules relation/edge.
	VersionRulesTable = "version_rules"
	// VersionRulesInverseTable is the table name for the VersionRule entity.
	// It exists in this package in order to avoid circular dependency with the "versionrule" package.
	VersionRulesInverseTable = "version_rules"
	// VersionRulesColumn is the table column denoting the version_rules relation/edge.
	VersionRulesColumn = "exam_id"
)

// Columns holds all SQL columns for exam fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldDescription,
	FieldTimeLimit,
	FieldIsActive,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
)

// OrderOption defines the ordering options for the Exam queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByTimeLimit orders the results by the time_limit field.
func ByTimeLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeLimit, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// BySectionsCount orders the results by sections count.
func BySectionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSectionsStep(), opts...)
	}
}

// BySections orders the results by sections terms.
func BySections(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSectionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTopicsCount orders the results by topics count.
func ByTopicsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTopicsStep(), opts...)
	}
}

// ByTopics orders the results by topics terms.
func ByTopics(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTopicsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUnitsCount orders the results by units count.
func ByUnitsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUnitsStep(), opts...)
	}
}

// ByUnits orders the results by units terms.
func ByUnits(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUnitsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByVersionRulesCount orders the results by version_rules count.
func ByVersionRulesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVersionRulesStep(), opts...)
	}
}

// ByVersionRules orders the results by version_rules terms.
func ByVersionRules(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVersionRulesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSectionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SectionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SectionsTable, SectionsColumn),
	)
}
func newTopicsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TopicsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TopicsTable, TopicsColumn),
	)
}
func newUnitsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UnitsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UnitsTable, UnitsColumn),
	)
}
func newVersionRulesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VersionRulesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VersionRulesTable, VersionRulesColumn),
	)
}
