// Code generated by ent, DO NOT EDIT.

package problemtranslation

import (
	"examination/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldLTE(FieldID, id))
}

// Locale applies equality check predicate on the "locale" field. It's identical to LocaleEQ.
func Locale(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEQ(FieldLocale, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEQ(FieldTitle, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEQ(FieldContent, v))
}

// Explanation applies equality check predicate on the "explanation" field. It's identical to ExplanationEQ.
func Explanation(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEQ(FieldExplanation, v))
}

// ProblemID applies equality check predicate on the "problem_id" field. It's identical to ProblemIDEQ.
func ProblemID(v int) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEQ(FieldProblemID, v))
}

// LocaleEQ applies the EQ predicate on the "locale" field.
func LocaleEQ(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEQ(FieldLocale, v))
}

// LocaleNEQ applies the NEQ predicate on the "locale" field.
func LocaleNEQ(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldNEQ(FieldLocale, v))
}

// LocaleIn applies the In predicate on the "locale" field.
func LocaleIn(vs ...string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldIn(FieldLocale, vs...))
}

// LocaleNotIn applies the NotIn predicate on the "locale" field.
func LocaleNotIn(vs ...string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldNotIn(FieldLocale, vs...))
}

// LocaleGT applies the GT predicate on the "locale" field.
func LocaleGT(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldGT(FieldLocale, v))
}

// LocaleGTE applies the GTE predicate on the "locale" field.
func LocaleGTE(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldGTE(FieldLocale, v))
}

// LocaleLT applies the LT predicate on the "locale" field.
func LocaleLT(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldLT(FieldLocale, v))
}

// LocaleLTE applies the LTE predicate on the "locale" field.
func LocaleLTE(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldLTE(FieldLocale, v))
}

// LocaleContains applies the Contains predicate on the "locale" field.
func LocaleContains(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldContains(FieldLocale, v))
}

// LocaleHasPrefix applies the HasPrefix predicate on the "locale" field.
func LocaleHasPrefix(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldHasPrefix(FieldLocale, v))
}

// LocaleHasSuffix applies the HasSuffix predicate on the "locale" field.
func LocaleHasSuffix(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldHasSuffix(FieldLocale, v))
}

// LocaleEqualFold applies the EqualFold predicate on the "locale" field.
func LocaleEqualFold(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEqualFold(FieldLocale, v))
}

// LocaleContainsFold applies the ContainsFold predicate on the "locale" field.
func LocaleContainsFold(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldContainsFold(FieldLocale, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldContainsFold(FieldTitle, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldContainsFold(FieldContent, v))
}

// ExplanationEQ applies the EQ predicate on the "explanation" field.
func ExplanationEQ(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEQ(FieldExplanation, v))
}

// ExplanationNEQ applies the NEQ predicate on the "explanation" field.
func ExplanationNEQ(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldNEQ(FieldExplanation, v))
}

// ExplanationIn applies the In predicate on the "explanation" field.
func ExplanationIn(vs ...string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldIn(FieldExplanation, vs...))
}

// ExplanationNotIn applies the NotIn predicate on the "explanation" field.
func ExplanationNotIn(vs ...string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldNotIn(FieldExplanation, vs...))
}

// ExplanationGT applies the GT predicate on the "explanation" field.
func ExplanationGT(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldGT(FieldExplanation, v))
}

// ExplanationGTE applies the GTE predicate on the "explanation" field.
func ExplanationGTE(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldGTE(FieldExplanation, v))
}

// ExplanationLT applies the LT predicate on the "explanation" field.
func ExplanationLT(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldLT(FieldExplanation, v))
}

// ExplanationLTE applies the LTE predicate on the "explanation" field.
func ExplanationLTE(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldLTE(FieldExplanation, v))
}

// ExplanationContains applies the Contains predicate on the "explanation" field.
func ExplanationContains(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldContains(FieldExplanation, v))
}

// ExplanationHasPrefix applies the HasPrefix predicate on the "explanation" field.
func ExplanationHasPrefix(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldHasPrefix(FieldExplanation, v))
}

// ExplanationHasSuffix applies the HasSuffix predicate on the "explanation" field.
func ExplanationHasSuffix(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldHasSuffix(FieldExplanation, v))
}

// ExplanationIsNil applies the IsNil predicate on the "explanation" field.
func ExplanationIsNil() predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldIsNull(FieldExplanation))
}

// ExplanationNotNil applies the NotNil predicate on the "explanation" field.
func ExplanationNotNil() predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldNotNull(FieldExplanation))
}

// ExplanationEqualFold applies the EqualFold predicate on the "explanation" field.
func ExplanationEqualFold(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEqualFold(FieldExplanation, v))
}

// ExplanationContainsFold applies the ContainsFold predicate on the "explanation" field.
func ExplanationContainsFold(v string) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldContainsFold(FieldExplanation, v))
}

// ProblemIDEQ applies the EQ predicate on the "problem_id" field.
func ProblemIDEQ(v int) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldEQ(FieldProblemID, v))
}

// ProblemIDNEQ applies the NEQ predicate on the "problem_id" field.
func ProblemIDNEQ(v int) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldNEQ(FieldProblemID, v))
}

// ProblemIDIn applies the In predicate on the "problem_id" field.
func ProblemIDIn(vs ...int) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldIn(FieldProblemID, vs...))
}

// ProblemIDNotIn applies the NotIn predicate on the "problem_id" field.
func ProblemIDNotIn(vs ...int) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.FieldNotIn(FieldProblemID, vs...))
}

// HasProblem applies the HasEdge predicate on the "problem" edge.
func HasProblem() predicate.ProblemTranslation {
	return predicate.ProblemTranslation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProblemTable, ProblemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProblemWith applies the HasEdge predicate on the "problem" edge with a given conditions (other predicates).
func HasProblemWith(preds ...predicate.Problem) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(func(s *sql.Selector) {
		step := newProblemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChoices applies the HasEdge predicate on the "choices" edge.
func HasChoices() predicate.ProblemTranslation {
	return predicate.ProblemTranslation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChoicesTable, ChoicesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChoicesWith applies the HasEdge predicate on the "choices" edge with a given conditions (other predicates).
func HasChoicesWith(preds ...predicate.Choice) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(func(s *sql.Selector) {
		step := newChoicesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProblemTranslation) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProblemTranslation) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProblemTranslation) predicate.ProblemTranslation {
	return predicate.ProblemTranslation(sql.NotPredicates(p))
}
