// Code generated by ent, DO NOT EDIT.

package versionrule

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the versionrule type in the database.
	Label = "version_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldYear holds the string denoting the year field in the database.
	FieldYear = "year"
	// FieldRound holds the string denoting the round field in the database.
	FieldRound = "round"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldOperator holds the string denoting the operator field in the database.
	FieldOperator = "operator"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldExamID holds the string denoting the exam_id field in the database.
	FieldExamID = "exam_id"
	// FieldProblemID holds the string denoting the problem_id field in the database.
	FieldProblemID = "problem_id"
	// EdgeExam holds the string denoting the exam edge name in mutations.
	EdgeExam = "exam"
	// EdgeProblem holds the string denoting the problem edge name in mutations.
	EdgeProblem = "problem"
	// Table holds the table name of the versionrule in the database.
	Table = "version_rules"
	// ExamTable is the table that holds the exam relation/edge.
	ExamTable = "version_rules"
	// ExamInverseTable is the table name for the Exam entity.
	// It exists in this package in order to avoid circular dependency with the "exam" package.
	ExamInverseTable = "exams"
	// ExamColumn is the table column denoting the exam relation/edge.
	ExamColumn = "exam_id"
	// ProblemTable is the table that holds the problem relation/edge.
	ProblemTable = "version_rules"
	// ProblemInverseTable is the table name for the Problem entity.
	// It exists in this package in order to avoid circular dependency with the "problem" package.
	ProblemInverseTable = "problems"
	// ProblemColumn is the table column denoting the problem relation/edge.
	ProblemColumn = "problem_id"
)

// Columns holds all SQL columns for versionrule fields.
var Columns = []string{
	FieldID,
	FieldYear,
	FieldRound,
	FieldCategory,
	FieldOperator,
	FieldStatus,
	FieldExamID,
	FieldProblemID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Operator defines the type for the "operator" enum field.
type Operator string

// Operator values.
const (
	OperatorGT  Operator = "GT"
	OperatorGTE Operator = "GTE"
	OperatorLT  Operator = "LT"
	OperatorLTE Operator = "LTE"
	OperatorEQ  Operator = "EQ"
	OperatorNEQ Operator = "NEQ"
)

func (o Operator) String() string {
	return string(o)
}

// OperatorValidator is a validator for the "operator" field enum values. It is called by the builders before save.
func OperatorValidator(o Operator) error {
	switch o {
	case OperatorGT, OperatorGTE, OperatorLT, OperatorLTE, OperatorEQ, OperatorNEQ:
		return nil
	default:
		return fmt.Errorf("versionrule: invalid enum value for operator field: %q", o)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusACTIVE is the default value of the Status enum.
const DefaultStatus = StatusACTIVE

// Status values.
const (
	StatusACTIVE     Status = "ACTIVE"
	StatusDEPRECATED Status = "DEPRECATED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusACTIVE, StatusDEPRECATED:
		return nil
	default:
		return fmt.Errorf("versionrule: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the VersionRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByYear orders the results by the year field.
func ByYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYear, opts...).ToFunc()
}

// ByRound orders the results by the round field.
func ByRound(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRound, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByOperator orders the results by the operator field.
func ByOperator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperator, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByExamID orders the results by the exam_id field.
func ByExamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExamID, opts...).ToFunc()
}

// ByProblemID orders the results by the problem_id field.
func ByProblemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProblemID, opts...).ToFunc()
}

// ByExamField orders the results by exam field.
func ByExamField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExamStep(), sql.OrderByField(field, opts...))
	}
}

// ByProblemField orders the results by problem field.
func ByProblemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProblemStep(), sql.OrderByField(field, opts...))
	}
}
func newExamStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExamInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ExamTable, ExamColumn),
	)
}
func newProblemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProblemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProblemTable, ProblemColumn),
	)
}
