// Code generated by ent, DO NOT EDIT.

package versionrule

import (
	"examination/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldLTE(FieldID, id))
}

// Year applies equality check predicate on the "year" field. It's identical to YearEQ.
func Year(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldEQ(FieldYear, v))
}

// Round applies equality check predicate on the "round" field. It's identical to RoundEQ.
func Round(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldEQ(FieldRound, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldEQ(FieldCategory, v))
}

// ExamID applies equality check predicate on the "exam_id" field. It's identical to ExamIDEQ.
func ExamID(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldEQ(FieldExamID, v))
}

// ProblemID applies equality check predicate on the "problem_id" field. It's identical to ProblemIDEQ.
func ProblemID(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldEQ(FieldProblemID, v))
}

// YearEQ applies the EQ predicate on the "year" field.
func YearEQ(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldEQ(FieldYear, v))
}

// YearNEQ applies the NEQ predicate on the "year" field.
func YearNEQ(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNEQ(FieldYear, v))
}

// YearIn applies the In predicate on the "year" field.
func YearIn(vs ...int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldIn(FieldYear, vs...))
}

// YearNotIn applies the NotIn predicate on the "year" field.
func YearNotIn(vs ...int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNotIn(FieldYear, vs...))
}

// YearGT applies the GT predicate on the "year" field.
func YearGT(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldGT(FieldYear, v))
}

// YearGTE applies the GTE predicate on the "year" field.
func YearGTE(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldGTE(FieldYear, v))
}

// YearLT applies the LT predicate on the "year" field.
func YearLT(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldLT(FieldYear, v))
}

// YearLTE applies the LTE predicate on the "year" field.
func YearLTE(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldLTE(FieldYear, v))
}

// YearIsNil applies the IsNil predicate on the "year" field.
func YearIsNil() predicate.VersionRule {
	return predicate.VersionRule(sql.FieldIsNull(FieldYear))
}

// YearNotNil applies the NotNil predicate on the "year" field.
func YearNotNil() predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNotNull(FieldYear))
}

// RoundEQ applies the EQ predicate on the "round" field.
func RoundEQ(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldEQ(FieldRound, v))
}

// RoundNEQ applies the NEQ predicate on the "round" field.
func RoundNEQ(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNEQ(FieldRound, v))
}

// RoundIn applies the In predicate on the "round" field.
func RoundIn(vs ...int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldIn(FieldRound, vs...))
}

// RoundNotIn applies the NotIn predicate on the "round" field.
func RoundNotIn(vs ...int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNotIn(FieldRound, vs...))
}

// RoundGT applies the GT predicate on the "round" field.
func RoundGT(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldGT(FieldRound, v))
}

// RoundGTE applies the GTE predicate on the "round" field.
func RoundGTE(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldGTE(FieldRound, v))
}

// RoundLT applies the LT predicate on the "round" field.
func RoundLT(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldLT(FieldRound, v))
}

// RoundLTE applies the LTE predicate on the "round" field.
func RoundLTE(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldLTE(FieldRound, v))
}

// RoundIsNil applies the IsNil predicate on the "round" field.
func RoundIsNil() predicate.VersionRule {
	return predicate.VersionRule(sql.FieldIsNull(FieldRound))
}

// RoundNotNil applies the NotNil predicate on the "round" field.
func RoundNotNil() predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNotNull(FieldRound))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryIsNil applies the IsNil predicate on the "category" field.
func CategoryIsNil() predicate.VersionRule {
	return predicate.VersionRule(sql.FieldIsNull(FieldCategory))
}

// CategoryNotNil applies the NotNil predicate on the "category" field.
func CategoryNotNil() predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNotNull(FieldCategory))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldContainsFold(FieldCategory, v))
}

// OperatorEQ applies the EQ predicate on the "operator" field.
func OperatorEQ(v Operator) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldEQ(FieldOperator, v))
}

// OperatorNEQ applies the NEQ predicate on the "operator" field.
func OperatorNEQ(v Operator) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNEQ(FieldOperator, v))
}

// OperatorIn applies the In predicate on the "operator" field.
func OperatorIn(vs ...Operator) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldIn(FieldOperator, vs...))
}

// OperatorNotIn applies the NotIn predicate on the "operator" field.
func OperatorNotIn(vs ...Operator) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNotIn(FieldOperator, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNotIn(FieldStatus, vs...))
}

// ExamIDEQ applies the EQ predicate on the "exam_id" field.
func ExamIDEQ(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldEQ(FieldExamID, v))
}

// ExamIDNEQ applies the NEQ predicate on the "exam_id" field.
func ExamIDNEQ(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNEQ(FieldExamID, v))
}

// ExamIDIn applies the In predicate on the "exam_id" field.
func ExamIDIn(vs ...int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldIn(FieldExamID, vs...))
}

// ExamIDNotIn applies the NotIn predicate on the "exam_id" field.
func ExamIDNotIn(vs ...int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNotIn(FieldExamID, vs...))
}

// ProblemIDEQ applies the EQ predicate on the "problem_id" field.
func ProblemIDEQ(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldEQ(FieldProblemID, v))
}

// ProblemIDNEQ applies the NEQ predicate on the "problem_id" field.
func ProblemIDNEQ(v int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNEQ(FieldProblemID, v))
}

// ProblemIDIn applies the In predicate on the "problem_id" field.
func ProblemIDIn(vs ...int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldIn(FieldProblemID, vs...))
}

// ProblemIDNotIn applies the NotIn predicate on the "problem_id" field.
func ProblemIDNotIn(vs ...int) predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNotIn(FieldProblemID, vs...))
}

// ProblemIDIsNil applies the IsNil predicate on the "problem_id" field.
func ProblemIDIsNil() predicate.VersionRule {
	return predicate.VersionRule(sql.FieldIsNull(FieldProblemID))
}

// ProblemIDNotNil applies the NotNil predicate on the "problem_id" field.
func ProblemIDNotNil() predicate.VersionRule {
	return predicate.VersionRule(sql.FieldNotNull(FieldProblemID))
}

// HasExam applies the HasEdge predicate on the "exam" edge.
func HasExam() predicate.VersionRule {
	return predicate.VersionRule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ExamTable, ExamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExamWith applies the HasEdge predicate on the "exam" edge with a given conditions (other predicates).
func HasExamWith(preds ...predicate.Exam) predicate.VersionRule {
	return predicate.VersionRule(func(s *sql.Selector) {
		step := newExamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProblem applies the HasEdge predicate on the "problem" edge.
func HasProblem() predicate.VersionRule {
	return predicate.VersionRule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProblemTable, ProblemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProblemWith applies the HasEdge predicate on the "problem" edge with a given conditions (other predicates).
func HasProblemWith(preds ...predicate.Problem) predicate.VersionRule {
	return predicate.VersionRule(func(s *sql.Selector) {
		step := newProblemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VersionRule) predicate.VersionRule {
	return predicate.VersionRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VersionRule) predicate.VersionRule {
	return predicate.VersionRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VersionRule) predicate.VersionRule {
	return predicate.VersionRule(sql.NotPredicates(p))
}
